"use client";

import {FormEvent,useEffect,useState} from "react";

type Checklist={selected:boolean;weight:boolean;consent:boolean;entry:boolean};
type Squad=Record<string,Checklist>;
type Logistics={event:string;date:string;venue:string;travel:number;hotel:number;entries:number;extras:number};
type Closeout={actualTravel:number;actualHotel:number;actualEntries:number;actualExtras:number};
type Share={paid:number;custom:number|null;waived:boolean};
type Shares=Record<string,Share>;
type Funding={id:string;name:string;type:"Sponsor"|"Fundraiser"|"Grant";target:number;secured:number;status:"Prospect"|"Contacted"|"Confirmed"};
type FinanceChecks={statements:boolean;receipts:boolean;funding:boolean;balances:boolean;archive:boolean};

const athletes=["Charlie Baxter","Olivia Green","Hollie Haworth","Jamie Granville"];
const defaultLogistics:Logistics={event:"Peterborough Series",date:"",venue:"",travel:120,hotel:0,entries:120,extras:40};
const defaultCloseout:Closeout={actualTravel:120,actualHotel:0,actualEntries:120,actualExtras:40};
const defaultFunding:Funding[]=[{id:"local-sponsor",name:"Local business sponsor",type:"Sponsor",target:300,secured:0,status:"Prospect"},{id:"club-fundraiser",name:"Club fundraising event",type:"Fundraiser",target:500,secured:180,status:"Contacted"},{id:"youth-grant",name:"Youth sport grant",type:"Grant",target:750,secured:0,status:"Prospect"}];
const defaultChecks:FinanceChecks={statements:false,receipts:false,funding:false,balances:false,archive:false};
const money=(value:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(value);
const read=<T,>(key:string,fallback:T):T=>{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)||"null")??fallback}catch{return fallback}};
function useSaved<T>(key:string,fallback:T){const[state,setState]=useState<T>(()=>read(key,fallback));useEffect(()=>{const timer=setTimeout(()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{}},100);return()=>clearTimeout(timer)},[key,state]);return[state,setState] as const}
const eventTotal=(logistics:Logistics,closeout:Closeout)=>{const actual=closeout.actualTravel+closeout.actualHotel+closeout.actualEntries+closeout.actualExtras;return actual||logistics.travel+logistics.hotel+logistics.entries+logistics.extras};
const selectedAthletes=(squad:Squad)=>athletes.filter(name=>squad[name]?.selected);
const shareFor=(item:Share|undefined,equal:number)=>item?.waived?0:item?.custom??equal;

export function CostSharing({notice}:{notice:(message:string)=>void}){
 const logistics=read<Logistics>("fighteye-event-logistics-v1",defaultLogistics);const closeout=read<Closeout>("fighteye-event-closeout-v1",defaultCloseout);const squad=read<Squad>("fighteye-squad-selection-v1",{});const[shares,setShares]=useSaved<Shares>("fighteye-cost-sharing-v1",{});const selected=selectedAthletes(squad);const total=eventTotal(logistics,closeout);const equal=selected.length?total/selected.length:0;const allocated=selected.reduce((sum,name)=>sum+shareFor(shares[name],equal),0);const paid=selected.reduce((sum,name)=>sum+(shares[name]?.paid||0),0);const update=(name:string,change:Partial<Share>)=>setShares(current=>({...current,[name]:{paid:0,custom:null,waived:false,...current[name],...change}}));
 const resetEqual=()=>{setShares(current=>Object.fromEntries(Object.entries(current).map(([name,item])=>[name,{...item,custom:null,waived:false}])));notice("Equal cost split restored")};
 return <div className="financePath"><FinanceHero phase="64" label="EVENT COST SHARING" title="Turn the final event cost into clear family balances." text="Allocate the saved closeout total across the selected squad and record each payment without a separate spreadsheet." metric={money(Math.max(0,allocated-paid))} metricLabel="outstanding"/><section className="financeMetrics"><Metric label="Event total" value={money(total)} detail={logistics.event}/><Metric label="Selected squad" value={selected.length} detail="From Phase 58"/><Metric label="Allocated" value={money(allocated)} detail="Across the squad"/><Metric label="Paid" value={money(paid)} detail={selected.length&&paid>=allocated?"All settled":"Payments received"}/></section>{selected.length?<section className="shareGrid">{selected.map(name=>{const item=shares[name]||{paid:0,custom:null,waived:false},share=shareFor(item,equal),balance=Math.max(0,share-item.paid);return <article className={balance?"panel sharePerson":"panel sharePerson settled"} key={name}><div className="sharePersonHead"><i>{name.split(" ").map(part=>part[0]).join("")}</i><span><small>{item.waived?"CLUB FUNDED":balance?"BALANCE DUE":"SETTLED"}</small><h3>{name}</h3></span><b>{money(balance)}</b></div><div className="shareFields"><label>Allocated<input type="number" min="0" value={Math.round(share)} disabled={item.waived} onChange={event=>update(name,{custom:Math.max(0,Number(event.target.value)||0)})}/></label><label>Paid<input type="number" min="0" value={item.paid} disabled={item.waived} onChange={event=>update(name,{paid:Math.max(0,Number(event.target.value)||0)})}/></label></div><button className={item.waived?"waived":""} onClick={()=>update(name,{waived:!item.waived})}>{item.waived?"✓ Club covering cost":"Mark as club funded"}</button></article>})}</section>:<section className="panel financeEmpty"><i>£</i><h3>No squad selected</h3><p>Select athletes in Phase 58 before allocating event costs.</p></section>}<section className="panel financeFooter"><div><span className="eyebrow">COST ALLOCATION</span><h3>{selected.length?money(Math.max(0,allocated-paid))+" remains to collect":"Waiting for squad selection"}</h3><p>Custom amounts and club-funded places update the total automatically.</p></div><div><button onClick={resetEqual}>Reset equal split</button><button className="primary" disabled={!selected.length} onClick={()=>notice("Cost statements confirmed")}>Confirm statements</button></div></section></div>;
}

export function FundingHub({notice}:{notice:(message:string)=>void}){
 const[funding,setFunding]=useSaved<Funding[]>("fighteye-funding-hub-v1",defaultFunding);const[showForm,setShowForm]=useState(false);const target=funding.reduce((sum,item)=>sum+item.target,0);const secured=funding.reduce((sum,item)=>sum+item.secured,0);const confirmed=funding.filter(item=>item.status==="Confirmed").length;
 const update=(id:string,change:Partial<Funding>)=>setFunding(current=>current.map(item=>item.id===id?{...item,...change}:item));
 const add=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const name=String(data.get("name")||"").trim();const amount=Math.max(0,Number(data.get("amount"))||0);const type=String(data.get("type")) as Funding["type"];if(!name||!amount)return;setFunding(current=>[...current,{id:`fund-${Date.now()}`,name,type,target:amount,secured:0,status:"Prospect"}]);setShowForm(false);notice("Funding opportunity added")};
 return <div className="financePath"><FinanceHero phase="65" label="FUNDING HUB" title="Track every sponsor, fundraiser and grant in one place." text="Keep funding targets, progress and follow-up status visible for coaches and club administrators." metric={money(secured)} metricLabel="secured funding"/><section className="financeMetrics"><Metric label="Funding target" value={money(target)} detail="Across all opportunities"/><Metric label="Secured" value={money(secured)} detail={target?Math.round(secured/target*100)+"% of target":"No target set"}/><Metric label="Open opportunities" value={funding.length-confirmed} detail="Still in progress"/><Metric label="Confirmed" value={confirmed} detail="Ready to allocate"/></section><section className="fundingToolbar panel"><div><span className="eyebrow">FUNDING PIPELINE</span><h3>{funding.length} opportunities</h3></div><button className="primary" onClick={()=>setShowForm(current=>!current)}>{showForm?"Close form":"＋ Add opportunity"}</button></section>{showForm&&<form className="panel fundingForm" onSubmit={add}><label>Opportunity name<input name="name" required placeholder="Sponsor, fundraiser or grant"/></label><label>Type<select name="type"><option>Sponsor</option><option>Fundraiser</option><option>Grant</option></select></label><label>Target amount<input name="amount" type="number" min="1" required placeholder="500"/></label><button className="primary">Add to pipeline</button></form>}<section className="fundingGrid">{funding.map(item=>{const progress=Math.min(100,item.target?Math.round(item.secured/item.target*100):0);return <article className="panel fundingCard" key={item.id}><div className="fundingHead"><span><small>{item.type.toUpperCase()}</small><h3>{item.name}</h3></span><select aria-label={item.name+" status"} value={item.status} onChange={event=>update(item.id,{status:event.target.value as Funding["status"]})}><option>Prospect</option><option>Contacted</option><option>Confirmed</option></select></div><div className="fundingAmounts"><span><small>Target</small><b>{money(item.target)}</b></span><span><small>Secured</small><b>{money(item.secured)}</b></span></div><div className="fundingBar"><i style={{width:progress+"%"}}/></div><label>Secured amount<input type="number" min="0" max={item.target} value={item.secured} onChange={event=>update(item.id,{secured:Math.min(item.target,Math.max(0,Number(event.target.value)||0))})}/></label></article>})}</section><section className="panel financeFooter"><div><span className="eyebrow">FUNDING PROGRESS</span><h3>{money(Math.max(0,target-secured))} still to secure</h3><p>Confirmed funding feeds the finance control summary in Phase 66.</p></div><button className="primary" onClick={()=>notice("Funding pipeline shared with club administrators")}>Share funding summary</button></section></div>;
}

export function FinanceControl({notice,openCosts}:{notice:(message:string)=>void;openCosts:()=>void}){
 const logistics=read<Logistics>("fighteye-event-logistics-v1",defaultLogistics);const closeout=read<Closeout>("fighteye-event-closeout-v1",defaultCloseout);const squad=read<Squad>("fighteye-squad-selection-v1",{});const shares=read<Shares>("fighteye-cost-sharing-v1",{});const funding=read<Funding[]>("fighteye-funding-hub-v1",defaultFunding);const[checks,setChecks]=useSaved<FinanceChecks>("fighteye-finance-control-v1",defaultChecks);const selected=selectedAthletes(squad);const total=eventTotal(logistics,closeout);const equal=selected.length?total/selected.length:0;const allocated=selected.reduce((sum,name)=>sum+shareFor(shares[name],equal),0);const paid=selected.reduce((sum,name)=>sum+(shares[name]?.paid||0),0);const outstanding=Math.max(0,allocated-paid);const secured=funding.filter(item=>item.status==="Confirmed").reduce((sum,item)=>sum+item.secured,0);const exposure=Math.max(0,total-paid-secured);const keys=(Object.keys(checks) as (keyof FinanceChecks)[]);const done=keys.filter(key=>checks[key]).length;const labels:Record<keyof FinanceChecks,[string,string]>={statements:["Family statements issued","Each athlete has a clear balance"],receipts:["Receipts reconciled","Actual event costs are evidenced"],funding:["Funding allocated","Confirmed support applied to the event"],balances:["Balances settled","No athlete payment remains overdue"],archive:["Finance record archived","Event file is ready for audit"]};
 const share=async()=>{const text=`${logistics.event} finance · ${money(total)} cost · ${money(outstanding)} family balances · ${money(secured)} confirmed funding · ${money(exposure)} club exposure`;try{if(navigator.share)await navigator.share({title:"FightEye finance control",text});else{await navigator.clipboard.writeText(text);notice("Finance summary copied")}}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;notice("Could not share finance summary")}};
 return <div className="financePath"><FinanceHero phase="66" label="FINANCE CONTROL" title="See the complete financial position before closing the file." text="Bring event cost, family payments, secured funding and audit checks into one decision-ready view." metric={money(exposure)} metricLabel="club exposure"/><section className="financeMetrics"><Metric label="Event cost" value={money(total)} detail={logistics.event}/><Metric label="Family balances" value={money(outstanding)} detail="Still outstanding"/><Metric label="Confirmed funding" value={money(secured)} detail="Available support"/><Metric label="Club exposure" value={money(exposure)} detail={exposure?"Requires action":"Fully covered"}/></section><section className="financeControlLayout"><article className="panel financePosition"><div className="financePositionTop"><div><span className="eyebrow">FINANCIAL POSITION</span><h3>{logistics.event}</h3></div><i className={exposure?"attention":"clear"}>{exposure?"ACTION":"CLEAR"}</i></div>{[["Final event cost",total],["Family payments",-paid],["Confirmed funding",-secured],["Club exposure",exposure]].map(([label,value],index)=><div className={index===3?"positionRow total":"positionRow"} key={String(label)}><span>{label}</span><b>{Number(value)<0?"−":""}{money(Math.abs(Number(value)))}</b></div>)}<button onClick={openCosts}>Review athlete cost sharing →</button></article><article className="panel financeChecklist"><div><span className="eyebrow">FINANCE CLOSE CHECKS</span><h3>{done}/{keys.length} complete</h3></div>{keys.map(key=><button className={checks[key]?"checked":""} key={key} onClick={()=>setChecks(current=>({...current,[key]:!current[key]}))}><i>{checks[key]?"✓":""}</i><span><b>{labels[key][0]}</b><small>{labels[key][1]}</small></span></button>)}</article></section><section className="panel financeFooter"><div><span className="eyebrow">CLUB FINANCE</span><h3>{done===keys.length&&exposure===0?"Finance cycle complete":keys.length-done+" checks and "+money(exposure)+" exposure remain"}</h3><p>The finance record stays editable until every payment and audit check is complete.</p></div><div><button onClick={share}>Share summary</button><button className="primary" disabled={done!==keys.length||exposure>0} onClick={()=>notice("Finance record approved and closed")}>Approve finance close</button></div></section></div>;
}

function FinanceHero({phase,label,title,text,metric,metricLabel}:{phase:string;label:string;title:string;text:string;metric:string;metricLabel:string}){return <section className="financeHero"><div><span className="badge gold">PHASE {phase} · {label}</span><h2>{title}</h2><p>{text}</p></div><aside><b>{metric}</b><span>{metricLabel}</span></aside></section>}
function Metric({label,value,detail}:{label:string;value:string|number;detail:string}){return <article><small>{label}</small><b>{value}</b><span>{detail}</span></article>}
