"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {BoutStatus,coaches,initialAssignments,initialLiveBouts,LiveBout,minutes,statusOrder} from "./competition-live-data";

type Result={placing:"Pending"|"Gold"|"Silver"|"Bronze"|"Win"|"Loss";score:string;verified:boolean};
const resultDefault:Result={placing:"Pending",score:"",verified:false};
const readValue=<T,>(key:string,fallback:T):T=>{if(typeof window==="undefined")return fallback;try{const value=JSON.parse(localStorage.getItem(key)||"null");return value??fallback}catch{return fallback}};
const readBouts=()=>{const value=readValue<unknown>("fighteye-live-bouts-v1",initialLiveBouts);return Array.isArray(value)&&value.every(item=>item&&typeof item==="object"&&typeof (item as LiveBout).id==="string")?value as LiveBout[]:initialLiveBouts};
const storeValue=(key:string,value:unknown)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
const downloadCsv=(filename:string,rows:string[][])=>{const csv=rows.map(row=>row.map(value=>'"'+value.replaceAll('"','""')+'"').join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};

export function LiveRingBoard({notice}:{notice:(message:string)=>void}){
 const[bouts,setBouts]=useState<LiveBout[]>(readBouts);const[filter,setFilter]=useState<"All"|BoutStatus>("All");const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>storeValue("fighteye-live-bouts-v1",bouts),100);return()=>{if(timer.current)clearTimeout(timer.current)}},[bouts]);
 const visible=bouts.filter(bout=>filter==="All"||bout.status===filter);const live=bouts.filter(bout=>bout.status==="Live").length;const calls=bouts.filter(bout=>bout.status==="Call").length;
 const advance=(id:string)=>setBouts(current=>current.map(bout=>{if(bout.id!==id)return bout;const next=statusOrder[Math.min(statusOrder.indexOf(bout.status)+1,statusOrder.length-1)];notice(bout.athlete+" moved to "+next);return{...bout,status:next}}));
 return <div className="liveSuite"><section className="liveHero"><div><span className="badge gold">PHASE 48 · LIVE RING & RUNNING ORDER</span><h2>Every fighter. Every ring. One live board.</h2><p>Keep the Prestige team moving from queue to call, ring and completion without losing the next bout.</p></div><div className="liveNow"><i></i><span><b>{live||calls}</b> active calls</span><small>{bouts.length} team bouts today</small></div></section>
 <section className="liveMetrics"><article><small>Live now</small><b>{live}</b><span>On the mats</span></article><article><small>Call area</small><b>{calls}</b><span>Coach needed now</span></article><article><small>Next 30 mins</small><b>{bouts.filter(bout=>bout.status==="Queued").length}</b><span>Prepare athletes</span></article><article><small>Complete</small><b>{bouts.filter(bout=>bout.status==="Complete").length}</b><span>Results ready</span></article></section>
 <section className="liveFilters panel">{(["All","Live","Call","Queued","Complete"] as const).map(item=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item}</button>)}<button className="refresh" onClick={()=>notice("Running order refreshed")}>↻ Refresh</button></section>
 <section className="ringBoard">{visible.map(bout=><article className={"ringBout panel "+bout.status.toLowerCase()} key={bout.id}><div className="ringBoutTop"><span className={"liveState "+bout.status.toLowerCase()}>{bout.status==="Live"?"● LIVE":bout.status.toUpperCase()}</span><b>{bout.time}</b><strong>{bout.ring}</strong></div><div className="ringAthlete"><span>{bout.athlete.split(" ").map(part=>part[0]).join("")}</span><div><small>{bout.category} · {bout.division}</small><h3>{bout.athlete}</h3><p>vs {bout.opponent} · {bout.stage}</p></div></div><button disabled={bout.status==="Complete"} onClick={()=>advance(bout.id)}>{bout.status==="Queued"?"Move to call":bout.status==="Call"?"Start bout":bout.status==="Live"?"Mark complete":"Completed ✓"}</button></article>)}</section></div>
}

export function CoachClashBoard({notice}:{notice:(message:string)=>void}){
 const[bouts]=useState<LiveBout[]>(readBouts);const[assignments,setAssignments]=useState<Record<string,string>>(()=>readValue("fighteye-coach-assignments-v1",initialAssignments));const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>storeValue("fighteye-coach-assignments-v1",assignments),100);return()=>{if(timer.current)clearTimeout(timer.current)}},[assignments]);
 const clashes=useMemo(()=>{const ids=new Set<string>();for(let i=0;i<bouts.length;i++)for(let j=i+1;j<bouts.length;j++){const a=bouts[i],b=bouts[j];if(a.status!=="Complete"&&b.status!=="Complete"&&assignments[a.id]===assignments[b.id]&&a.ring!==b.ring&&Math.abs(minutes(a.time)-minutes(b.time))<=15){ids.add(a.id);ids.add(b.id)}}return ids},[assignments,bouts]);
 const balance=()=>{const next={...assignments};const ordered=[...bouts].sort((a,b)=>minutes(a.time)-minutes(b.time));ordered.forEach((bout,index)=>{next[bout.id]=coaches[index%coaches.length]});setAssignments(next);notice("Coach cover auto-balanced")};
 return <div className="liveSuite"><section className="coachHero"><div><span className="badge gold">PHASE 49 · COACH ASSIGNMENT</span><h2>Stop ring clashes before they happen.</h2><p>Assign each Prestige bout, expose overlapping calls and rebalance coach cover in one tap.</p></div><div className={"clashCount "+(clashes.size?"danger":"clear")}><b>{clashes.size}</b><span>{clashes.size?"clashing bouts":"no clashes"}</span></div></section>
 <section className="coachToolbar panel"><div><b>{bouts.length} bouts</b><span> · {coaches.length} coaches · 15-minute clash window</span></div><button onClick={balance}>✦ Auto-balance cover</button></section>
 <section className="coachGrid">{bouts.map(bout=><article className={"coachAssignment panel "+(clashes.has(bout.id)?"hasClash":"")} key={bout.id}><div className="coachTime"><b>{bout.time}</b><span>{bout.ring}</span></div><div className="coachFight"><small>{bout.category} · {bout.stage}</small><h3>{bout.athlete}</h3><p>vs {bout.opponent}</p></div>{clashes.has(bout.id)&&<strong>! Coach clash</strong>}<label><span>Assigned coach</span><select value={assignments[bout.id]||coaches[0]} onChange={event=>setAssignments(current=>({...current,[bout.id]:event.target.value}))}>{coaches.map(coach=><option key={coach}>{coach}</option>)}</select></label></article>)}</section></div>
}

export function ResultsMedalCentre({notice}:{notice:(message:string)=>void}){
 const[bouts]=useState<LiveBout[]>(readBouts);const[results,setResults]=useState<Record<string,Result>>(()=>readValue("fighteye-results-v1",{}));const[filter,setFilter]=useState<"All"|"Medals"|"Unverified">("All");const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>storeValue("fighteye-results-v1",results),100);return()=>{if(timer.current)clearTimeout(timer.current)}},[results]);
 const update=(id:string,change:Partial<Result>)=>setResults(current=>({...current,[id]:{...(current[id]||resultDefault),...change}}));const value=(id:string)=>results[id]||resultDefault;const medals=["Gold","Silver","Bronze"] as const;const tally=medals.map(medal=>results?Object.values(results).filter(result=>result.placing===medal).length:0);const visible=bouts.filter(bout=>filter==="All"||filter==="Medals"&&medals.includes(value(bout.id).placing as typeof medals[number])||filter==="Unverified"&&!value(bout.id).verified);
 const exportResults=()=>{downloadCsv("prestige-results.csv",[["Bout","Athlete","Category","Opponent","Result","Score","Verified"],...bouts.map(bout=>[bout.id,bout.athlete,bout.category,bout.opponent,value(bout.id).placing,value(bout.id).score,value(bout.id).verified?"Yes":"No"])]);notice("Competition results exported")};
 return <div className="liveSuite"><section className="resultsHero"><div><span className="badge gold">PHASE 50 · RESULTS & MEDALS</span><h2>Capture the result while it is fresh.</h2><p>Record scores, verify outcomes and keep the Prestige medal table current from ringside.</p></div><div className="medalStack">{medals.map((medal,index)=><span className={medal.toLowerCase()} key={medal}><i>{["●","●","●"][index]}</i><b>{tally[index]}</b><small>{medal}</small></span>)}</div></section>
 <section className="resultMetrics"><article><small>Gold</small><b>{tally[0]}</b></article><article><small>Silver</small><b>{tally[1]}</b></article><article><small>Bronze</small><b>{tally[2]}</b></article><article><small>Verified</small><b>{Object.values(results).filter(result=>result.verified).length}/{bouts.length}</b></article></section>
 <section className="resultToolbar panel"><div>{(["All","Medals","Unverified"] as const).map(item=><button className={filter===item?"active":""} key={item} onClick={()=>setFilter(item)}>{item}</button>)}</div><button className="exportResults" onClick={exportResults}>⇩ Export results</button></section>
 <section className="resultList">{visible.map(bout=>{const result=value(bout.id);return <article className="resultCard panel" key={bout.id}><div className="resultIdentity"><span>{bout.athlete.split(" ").map(part=>part[0]).join("")}</span><div><small>{bout.id} · {bout.category} · {bout.stage}</small><h3>{bout.athlete}</h3><p>vs {bout.opponent}</p></div></div><div className="resultInputs"><label>Outcome<select value={result.placing} onChange={event=>update(bout.id,{placing:event.target.value as Result["placing"]})}>{["Pending","Gold","Silver","Bronze","Win","Loss"].map(item=><option key={item}>{item}</option>)}</select></label><label>Score<input value={result.score} onChange={event=>update(bout.id,{score:event.target.value})} placeholder="e.g. 10–7"/></label></div><button className={result.verified?"verified":""} onClick={()=>{update(bout.id,{verified:!result.verified});notice(result.verified?"Result returned to review":"Result verified")}}>{result.verified?"✓ Verified":"Verify result"}</button></article>})}</section></div>
}
