"use client";

import {useEffect,useState} from "react";

type Plan={focus:string;target:string;sessions:number;done:number;owner:string;complete:boolean};
type Plans=Record<string,Plan>;
type CheckIn={technique:number;confidence:number;fitness:number;note:string};
type Progress=Record<string,CheckIn>;
type Choice="Target"|"Consider"|"Skip";
type SeasonChoices=Record<string,Choice>;

const names=["Charlie Baxter","Olivia Green","Hollie Haworth","Jamie Granville"];
const initials=(name:string)=>name.split(" ").map(part=>part[0]).join("");
const read=<T,>(key:string,fallback:T):T=>{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)||"null")??fallback}catch{return fallback}};
const reviewSeed=()=>{const review=read<{athletes?:Record<string,{development?:string;action?:string}>}>("fighteye-post-event-review-v1",{});return Object.fromEntries(names.map(name=>[name,{focus:review.athletes?.[name]?.development||"First-exchange control",target:review.athletes?.[name]?.action||"Complete three focused rounds each week",sessions:6,done:0,owner:"Will Taylor",complete:false}])) as Plans};
const blankProgress=()=>Object.fromEntries(names.map(name=>[name,{technique:3,confidence:3,fitness:3,note:""}])) as Progress;

function useSavedState<T>(key:string,initial:()=>T){
 const[state,setState]=useState<T>(()=>read(key,initial()));
 useEffect(()=>{const timer=setTimeout(()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{}},100);return()=>clearTimeout(timer)},[key,state]);
 return[state,setState] as const;
}

export function DevelopmentPlans({notice}:{notice:(message:string)=>void}){
 const[plans,setPlans]=useSavedState<Plans>("fighteye-development-plans-v1",reviewSeed);const completed=Object.values(plans).filter(plan=>plan.complete).length;const delivered=Object.values(plans).reduce((sum,plan)=>sum+plan.done,0);const scheduled=Object.values(plans).reduce((sum,plan)=>sum+plan.sessions,0);
 const update=(name:string,change:Partial<Plan>)=>setPlans(current=>({...current,[name]:{...current[name],...change}}));
 return <div className="developmentPath"><PathHero phase="53" label="DEVELOPMENT PLANS" title="Turn reviews into a focused training block." text="Every athlete gets one priority, one measurable target and a clear coaching owner." metric={completed+"/"+names.length} metricLabel="plans complete"/>
 <section className="pathMetrics"><Metric label="Athlete plans" value={names.length} detail="From the latest review"/><Metric label="Sessions delivered" value={delivered+"/"+scheduled} detail="Current training block"/><Metric label="Actions complete" value={completed} detail="Coach confirmed"/><Metric label="Block length" value="6 weeks" detail="Editable per athlete"/></section>
 <section className="planGrid">{names.map(name=>{const plan=plans[name]||reviewSeed()[name];const percent=Math.min(100,Math.round(plan.done/Math.max(1,plan.sessions)*100));return <article className="panel planCard" key={name}><div className="pathAthleteHead"><i>{initials(name)}</i><span><small>ATHLETE DEVELOPMENT PLAN</small><h3>{name}</h3></span><b className={plan.complete?"ready":"active"}>{plan.complete?"Complete":"Active"}</b></div><label>Priority focus<input value={plan.focus} onChange={event=>update(name,{focus:event.target.value,complete:false})}/></label><label>Measurable outcome<textarea value={plan.target} onChange={event=>update(name,{target:event.target.value,complete:false})}/></label><div className="planControls"><label>Coach<select value={plan.owner} onChange={event=>update(name,{owner:event.target.value})}><option>Will Taylor</option><option>Saf</option><option>Trevor Digan</option></select></label><label>Target sessions<input type="number" min="1" max="30" value={plan.sessions} onChange={event=>update(name,{sessions:Math.max(1,Number(event.target.value)||1)})}/></label></div><div className="pathProgress"><span><i style={{width:percent+"%"}}/></span><b>{plan.done}/{plan.sessions}</b></div><div className="planActions"><button onClick={()=>update(name,{done:Math.max(0,plan.done-1),complete:false})}>− Session</button><button onClick={()=>update(name,{done:Math.min(plan.sessions,plan.done+1),complete:plan.done+1>=plan.sessions})}>＋ Session</button><button className={plan.complete?"complete":""} onClick={()=>update(name,{complete:!plan.complete})}>{plan.complete?"Reopen":"Complete plan"}</button></div></article>})}</section>
 <section className="panel pathFooter"><div><span className="eyebrow">TRAINING BLOCK CONTROL</span><h3>Publish this block to the coaching team</h3><p>{completed===names.length?"All athlete plans are complete.":names.length-completed+" athlete plans still need completion."}</p></div><button className="primary" onClick={()=>notice("Development block published to coaches")}>Publish training block</button></section></div>;
}

export function ProgressTracking({notice}:{notice:(message:string)=>void}){
 const[plans]=useSavedState<Plans>("fighteye-development-plans-v1",reviewSeed);const[progress,setProgress]=useSavedState<Progress>("fighteye-progress-tracking-v1",blankProgress);const defaults=blankProgress();const update=(name:string,change:Partial<CheckIn>)=>setProgress(current=>({...current,[name]:{...(current[name]||defaults[name]),...change}}));const average=(item:CheckIn)=>Math.round((item.technique+item.confidence+item.fitness)/15*100);const clubScore=Math.round(names.reduce((sum,name)=>sum+average(progress[name]||defaults[name]),0)/names.length);const delivered=Object.values(plans).reduce((sum,plan)=>sum+plan.done,0);const scheduled=Object.values(plans).reduce((sum,plan)=>sum+plan.sessions,0);
 return <div className="developmentPath"><PathHero phase="54" label="PROGRESS TRACKING" title="Measure whether the training block is working." text="Log technical execution, confidence and competition fitness in one quick weekly check-in." metric={clubScore+"%"} metricLabel="club readiness"/>
 <section className="pathMetrics"><Metric label="Club readiness" value={clubScore+"%"} detail="Three-dimension average"/><Metric label="Sessions complete" value={delivered} detail={scheduled+" scheduled"}/><Metric label="Athletes on track" value={names.filter(name=>average(progress[name]||defaults[name])>=67).length} detail="Readiness at 67%+"/><Metric label="Check-in cycle" value="Weekly" detail="Coach-owned evidence"/></section>
 <section className="progressGrid">{names.map(name=>{const item=progress[name]||defaults[name],score=average(item),plan=plans[name]||reviewSeed()[name];return <article className="panel progressCard" key={name}><div className="pathAthleteHead"><i>{initials(name)}</i><span><small>{plan.focus}</small><h3>{name}</h3></span><strong>{score}%</strong></div>{(["technique","confidence","fitness"] as const).map(key=><label className="scoreRow" key={key}><span>{key}<b>{item[key]}/5</b></span><input aria-label={name+" "+key} type="range" min="1" max="5" value={item[key]} onChange={event=>update(name,{[key]:Number(event.target.value)})}/></label>)}<label>Weekly evidence<textarea value={item.note} onChange={event=>update(name,{note:event.target.value})} placeholder="What changed in training this week?"/></label><div className="readinessBand"><span style={{width:score+"%"}}/><b>{score>=80?"Competition ready":score>=67?"On track":"Needs intervention"}</b></div></article>})}</section>
 <section className="panel pathFooter"><div><span className="eyebrow">WEEKLY CHECK-IN</span><h3>Evidence saved for season planning</h3><p>Readiness scores automatically feed Phase 55 recommendations.</p></div><button className="primary" onClick={()=>notice("Weekly progress check-in saved")}>Confirm weekly check-in</button></section></div>;
}

const seasonEvents=[{id:"autumn-open",name:"Autumn Open",date:"October 2026",level:"Development",load:1},{id:"peterborough",name:"Peterborough Series",date:"November 2026",level:"Domestic",load:2},{id:"winter-cup",name:"Winter Cup",date:"December 2026",level:"Development",load:1},{id:"english-open",name:"English Open",date:"Early 2027",level:"National",load:3}];

export function SeasonPlanner({notice}:{notice:(message:string)=>void}){
 const[progress]=useSavedState<Progress>("fighteye-progress-tracking-v1",blankProgress);const[choices,setChoices]=useSavedState<SeasonChoices>("fighteye-season-choices-v1",()=>({}));const defaults=blankProgress();const readiness=Math.round(names.reduce((sum,name)=>{const item=progress[name]||defaults[name];return sum+((item.technique+item.confidence+item.fitness)/15*100)},0)/names.length);const targetCount=Object.values(choices).filter(choice=>choice==="Target").length;const suggested:Choice=readiness>=78?"Target":readiness>=65?"Consider":"Skip";
 return <div className="developmentPath"><PathHero phase="55" label="SEASON INTELLIGENCE" title="Choose events that match athlete readiness." text="Balance development value, competition level and current evidence before committing the team." metric={readiness+"%"} metricLabel="readiness evidence"/>
 <section className="pathMetrics"><Metric label="Team readiness" value={readiness+"%"} detail="From Phase 54"/><Metric label="Target events" value={targetCount} detail="Selected for the season"/><Metric label="Planning horizon" value="4 events" detail="Dates require confirmation"/><Metric label="Suggested decision" value={suggested} detail="Evidence-led starting point"/></section>
 <section className="seasonBoard">{seasonEvents.map(event=>{const choice=choices[event.id]||"Consider";const fit=Math.max(45,Math.min(96,readiness-(event.load-1)*9));return <article className="panel seasonEvent" key={event.id}><div className="seasonDate"><small>PLANNING DATE</small><b>{event.date}</b></div><div><span className="badge">{event.level}</span><h3>{event.name}</h3><p>Estimated team fit based on current readiness and event level.</p></div><div className="fitScore"><b>{fit}%</b><span>team fit</span></div><div className="choiceGroup" aria-label={event.name+" decision"}>{(["Target","Consider","Skip"] as Choice[]).map(option=><button aria-pressed={choice===option} className={choice===option?"active "+option.toLowerCase():""} key={option} onClick={()=>setChoices(current=>({...current,[event.id]:option}))}>{option}</button>)}</div></article>})}</section>
 <section className="panel pathwayFlow"><span><b>52</b>Review</span><i>→</i><span><b>53</b>Plan</span><i>→</i><span><b>54</b>Track</span><i>→</i><span className="current"><b>55</b>Select</span></section>
 <section className="panel pathFooter"><div><span className="eyebrow">SEASON CONTROL</span><h3>{targetCount?targetCount+" events selected":"No events targeted yet"}</h3><p>Competition dates remain planning entries until confirmed against official sources.</p></div><button className="primary" onClick={()=>notice("Season pathway saved")}>Save season pathway</button></section></div>;
}

function PathHero({phase,label,title,text,metric,metricLabel}:{phase:string;label:string;title:string;text:string;metric:string;metricLabel:string}){return <section className="pathHero"><div><span className="badge gold">PHASE {phase} · {label}</span><h2>{title}</h2><p>{text}</p></div><aside><b>{metric}</b><span>{metricLabel}</span></aside></section>}
function Metric({label,value,detail}:{label:string;value:string|number;detail:string}){return <article><small>{label}</small><b>{value}</b><span>{detail}</span></article>}
