"use client";

import {useEffect,useState} from "react";

type Checklist={selected:boolean;weight:boolean;consent:boolean;entry:boolean};
type Squad=Record<string,Checklist>;
type Condition="Good"|"Monitor"|"Replace";
type InventoryItem={id:string;name:string;category:string;quantity:number;available:number;condition:Condition;serviceDate:string};
type KitKey="headguard"|"gloves"|"footpads"|"mouthguard"|"uniform"|"licence";
type KitAllocation=Record<string,Record<KitKey,boolean>>;
type Compliance={firstAid:boolean;coachCredentials:boolean;safeguarding:boolean;emergencyContacts:boolean;insurance:boolean;riskAssessment:boolean};

const athletes=["Charlie Baxter","Olivia Green","Hollie Haworth","Jamie Granville"];
const kitKeys:KitKey[]=["headguard","gloves","footpads","mouthguard","uniform","licence"];
const kitLabels:Record<KitKey,string>={headguard:"Headguard",gloves:"Gloves",footpads:"Foot pads",mouthguard:"Mouthguard",uniform:"Competition uniform",licence:"Licence / ID"};
const defaultInventory:InventoryItem[]=[{id:"headguards",name:"Competition headguards",category:"Headguard",quantity:8,available:6,condition:"Good",serviceDate:"2026-10-01"},{id:"gloves",name:"Competition gloves",category:"Gloves",quantity:10,available:8,condition:"Good",serviceDate:"2026-10-01"},{id:"footpads",name:"Foot protectors",category:"Foot pads",quantity:8,available:7,condition:"Monitor",serviceDate:"2026-09-20"},{id:"body",name:"Body protectors",category:"Body protection",quantity:6,available:5,condition:"Good",serviceDate:"2026-11-01"},{id:"first-aid",name:"First-aid kits",category:"Safety",quantity:2,available:2,condition:"Good",serviceDate:"2026-09-30"}];
const defaultCompliance:Compliance={firstAid:false,coachCredentials:false,safeguarding:false,emergencyContacts:false,insurance:false,riskAssessment:false};
const read=<T,>(key:string,fallback:T):T=>{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)||"null")??fallback}catch{return fallback}};
function useSaved<T>(key:string,fallback:T){const[state,setState]=useState<T>(()=>read(key,fallback));useEffect(()=>{const timer=setTimeout(()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{}},100);return()=>clearTimeout(timer)},[key,state]);return[state,setState] as const}
const selectedAthletes=(squad:Squad)=>athletes.filter(name=>squad[name]?.selected);
const emptyKit=():Record<KitKey,boolean>=>({headguard:false,gloves:false,footpads:false,mouthguard:false,uniform:false,licence:false});
const initials=(name:string)=>name.split(" ").map(part=>part[0]).join("");

export function EquipmentInventory({notice}:{notice:(message:string)=>void}){
 const[items,setItems]=useSaved<InventoryItem[]>("fighteye-equipment-inventory-v1",defaultInventory);const total=items.reduce((sum,item)=>sum+item.quantity,0);const available=items.reduce((sum,item)=>sum+item.available,0);const attention=items.filter(item=>item.condition!=="Good"||item.available<Math.ceil(item.quantity/2)).length;const update=(id:string,change:Partial<InventoryItem>)=>setItems(current=>current.map(item=>item.id===id?{...item,...change}:item));
 return <div className="safetyPath"><SafetyHero phase="67" label="EQUIPMENT INVENTORY" title="Know what the club owns and what is safe to issue." text="Track stock, availability, condition and inspection dates for competition equipment." metric={available+"/"+total} metricLabel="items available"/><section className="safetyMetrics"><Metric label="Stock items" value={total} detail="Across all categories"/><Metric label="Available" value={available} detail="Ready to allocate"/><Metric label="On loan / unavailable" value={total-available} detail="Currently assigned"/><Metric label="Needs attention" value={attention} detail="Condition or stock level"/></section><section className="inventoryGrid">{items.map(item=><article className={item.condition==="Good"?"panel inventoryCard":"panel inventoryCard attention"} key={item.id}><div className="inventoryHead"><i>{item.category==="Safety"?"+":"◇"}</i><span><small>{item.category.toUpperCase()}</small><h3>{item.name}</h3></span><select aria-label={item.name+" condition"} value={item.condition} onChange={event=>update(item.id,{condition:event.target.value as Condition})}><option>Good</option><option>Monitor</option><option>Replace</option></select></div><div className="stockNumbers"><span><small>TOTAL</small><b>{item.quantity}</b></span><span><small>AVAILABLE</small><b>{item.available}</b></span><span><small>ISSUED</small><b>{Math.max(0,item.quantity-item.available)}</b></span></div><div className="stockAdjust"><button aria-label={"Reduce available "+item.name} onClick={()=>update(item.id,{available:Math.max(0,item.available-1)})}>−</button><strong>{item.available} ready</strong><button aria-label={"Increase available "+item.name} onClick={()=>update(item.id,{available:Math.min(item.quantity,item.available+1)})}>＋</button></div><label>Next inspection<input type="date" value={item.serviceDate} onChange={event=>update(item.id,{serviceDate:event.target.value})}/></label></article>)}</section><section className="panel safetyFooter"><div><span className="eyebrow">STOCK CONTROL</span><h3>{attention?attention+" equipment lines need attention":"All equipment is serviceable"}</h3><p>Availability feeds directly into athlete kit allocation.</p></div><button className="primary" onClick={()=>notice("Equipment inventory confirmed")}>Confirm inventory</button></section></div>;
}

export function KitAllocation({notice}:{notice:(message:string)=>void}){
 const squad=read<Squad>("fighteye-squad-selection-v1",{});const inventory=read<InventoryItem[]>("fighteye-equipment-inventory-v1",defaultInventory);const[kit,setKit]=useSaved<KitAllocation>("fighteye-kit-allocation-v1",{});const selected=selectedAthletes(squad);const completed=selected.filter(name=>kitKeys.every(key=>kit[name]?.[key])).length;const update=(name:string,key:KitKey)=>setKit(current=>({...current,[name]:{...emptyKit(),...current[name],[key]:!current[name]?.[key]}}));const sharedNeeds:Record<string,number>={headguard:selected.filter(name=>kit[name]?.headguard).length,gloves:selected.filter(name=>kit[name]?.gloves).length,footpads:selected.filter(name=>kit[name]?.footpads).length};const stockFor=(category:string)=>inventory.find(item=>item.category===category)?.available||0;const shortages=[sharedNeeds.headguard-stockFor("Headguard"),sharedNeeds.gloves-stockFor("Gloves"),sharedNeeds.footpads-stockFor("Foot pads")].filter(value=>value>0).reduce((sum,value)=>sum+value,0);
 return <div className="safetyPath"><SafetyHero phase="68" label="KIT ALLOCATION" title="Give every selected athlete a complete competition kit." text="Assign shared protection and confirm personal essentials before the team travels." metric={completed+"/"+selected.length} metricLabel="athletes kit-ready"/><section className="safetyMetrics"><Metric label="Selected squad" value={selected.length} detail="From Phase 58"/><Metric label="Kit ready" value={completed} detail="All six checks complete"/><Metric label="Open checks" value={selected.length*kitKeys.length-selected.reduce((sum,name)=>sum+kitKeys.filter(key=>kit[name]?.[key]).length,0)} detail="Across the squad"/><Metric label="Stock conflicts" value={shortages} detail={shortages?"Resolve before approval":"Equipment available"}/></section>{selected.length?<section className="kitGrid">{selected.map(name=>{const record={...emptyKit(),...kit[name]},score=kitKeys.filter(key=>record[key]).length;return <article className={score===kitKeys.length?"panel kitCard complete":"panel kitCard"} key={name}><div className="kitHead"><i>{initials(name)}</i><span><small>{score===kitKeys.length?"KIT READY":score+"/"+kitKeys.length+" CHECKS"}</small><h3>{name}</h3></span><strong>{Math.round(score/kitKeys.length*100)}%</strong></div><div className="kitChecks">{kitKeys.map(key=><button className={record[key]?"checked":""} key={key} onClick={()=>update(name,key)}><i>{record[key]?"✓":""}</i><span>{kitLabels[key]}</span></button>)}</div></article>})}</section>:<section className="panel safetyEmpty"><i>◇</i><h3>No squad selected</h3><p>Select athletes in Phase 58 before allocating competition kit.</p></section>}<section className="panel safetyFooter"><div><span className="eyebrow">KIT CONTROL</span><h3>{shortages?shortages+" stock conflicts must be resolved":completed===selected.length&&selected.length?"The full squad is kit-ready":selected.length-completed+" athletes still need kit checks"}</h3><p>Shared stock and personal essentials must both be complete.</p></div><button className="primary" disabled={!selected.length||completed!==selected.length||shortages>0} onClick={()=>notice("Competition kit allocation approved")}>Approve kit allocation</button></section></div>;
}

export function SafetyCompliance({notice,openKit}:{notice:(message:string)=>void;openKit:()=>void}){
 const squad=read<Squad>("fighteye-squad-selection-v1",{});const inventory=read<InventoryItem[]>("fighteye-equipment-inventory-v1",defaultInventory);const kit=read<KitAllocation>("fighteye-kit-allocation-v1",{});const[checks,setChecks]=useSaved<Compliance>("fighteye-safety-compliance-v1",defaultCompliance);const selected=selectedAthletes(squad);const kitReady=selected.length>0&&selected.every(name=>kitKeys.every(key=>kit[name]?.[key]));const entriesReady=selected.length>0&&selected.every(name=>squad[name]?.weight&&squad[name]?.consent&&squad[name]?.entry);const equipmentReady=inventory.every(item=>item.condition!=="Replace")&&inventory.some(item=>item.category==="Safety"&&item.available>0);const complianceKeys=(Object.keys(checks) as (keyof Compliance)[]);const complianceReady=complianceKeys.every(key=>checks[key]);const gates=[{label:"Selected squad",detail:selected.length+" athletes",pass:selected.length>0},{label:"Entry and consent checks",detail:entriesReady?"Every athlete cleared":"Athlete checks incomplete",pass:entriesReady},{label:"Competition kit",detail:kitReady?"Full squad kit-ready":"Kit checks incomplete",pass:kitReady},{label:"Equipment condition",detail:equipmentReady?"Serviceable stock and first aid ready":"Inventory needs attention",pass:equipmentReady},{label:"Club compliance",detail:complianceKeys.filter(key=>checks[key]).length+"/"+complianceKeys.length+" checks",pass:complianceReady}];const passed=gates.filter(gate=>gate.pass).length;const ready=passed===gates.length;const labels:Record<keyof Compliance,[string,string]>={firstAid:["First-aid cover confirmed","Named person and kit available"],coachCredentials:["Coach credentials current","Qualifications and licences checked"],safeguarding:["Safeguarding lead available","Reporting route confirmed"],emergencyContacts:["Emergency contacts accessible","Current details available offline"],insurance:["Insurance verified","Club and athlete cover checked"],riskAssessment:["Event risk assessment complete","Travel, venue and competition risks reviewed"]};
 const share=async()=>{const text=`FightEye safety status · ${passed}/${gates.length} gates passed · ${selected.length} athletes · ${ready?"READY":"ACTION NEEDED"}`;try{if(navigator.share)await navigator.share({title:"FightEye safety compliance",text});else{await navigator.clipboard.writeText(text);notice("Safety summary copied")}}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;notice("Could not share safety summary")}};
 return <div className="safetyPath"><SafetyHero phase="69" label="SAFETY & COMPLIANCE" title="Make the final safety decision from one trusted view." text="Combine athlete clearance, competition kit, equipment condition and club compliance before approval." metric={Math.round(passed/gates.length*100)+"%"} metricLabel={ready?"competition ready":"safety readiness"}/><section className="complianceStatus panel"><div className={ready?"complianceDecision ready":"complianceDecision blocked"}><i>{ready?"✓":"!"}</i><span><small>FINAL DECISION</small><b>{ready?"READY TO COMPETE":"ACTION REQUIRED"}</b></span></div><button onClick={()=>window.print()}>Print safety pack</button></section><section className="complianceLayout"><article className="panel safetyGates"><div><span className="eyebrow">READINESS GATES</span><h3>{passed}/{gates.length} passed</h3></div>{gates.map(gate=><div className={gate.pass?"safetyGate pass":"safetyGate fail"} key={gate.label}><i>{gate.pass?"✓":"!"}</i><span><b>{gate.label}</b><small>{gate.detail}</small></span><strong>{gate.pass?"Ready":"Action"}</strong></div>)}<button onClick={openKit}>Review athlete kit →</button></article><article className="panel complianceChecks"><div><span className="eyebrow">CLUB COMPLIANCE</span><h3>Required confirmations</h3></div>{complianceKeys.map(key=><button className={checks[key]?"checked":""} key={key} onClick={()=>setChecks(current=>({...current,[key]:!current[key]}))}><i>{checks[key]?"✓":""}</i><span><b>{labels[key][0]}</b><small>{labels[key][1]}</small></span></button>)}</article></section><section className="panel safetyFooter"><div><span className="eyebrow">SAFETY APPROVAL</span><h3>{ready?"All competition safety gates are complete":gates.length-passed+" safety gates remain"}</h3><p>The status updates from saved squad, kit, inventory and compliance records.</p></div><div><button onClick={share}>Share summary</button><button className="primary" disabled={!ready} onClick={()=>notice("Competition safety pack approved")}>Approve safety pack</button></div></section></div>;
}

function SafetyHero({phase,label,title,text,metric,metricLabel}:{phase:string;label:string;title:string;text:string;metric:string;metricLabel:string}){return <section className="safetyHero"><div><span className="badge gold">PHASE {phase} · {label}</span><h2>{title}</h2><p>{text}</p></div><aside><b>{metric}</b><span>{metricLabel}</span></aside></section>}
function Metric({label,value,detail}:{label:string;value:string|number;detail:string}){return <article><small>{label}</small><b>{value}</b><span>{detail}</span></article>}
