"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {BoutStatus,coaches,initialAssignments,initialLiveBouts,LiveBout,minutes,statusOrder} from "./competition-live-data";
import {readActiveLiveEvent} from "./event-club-links";

type Result={placing:"Pending"|"Gold"|"Silver"|"Bronze"|"Win"|"Loss";score:string;verified:boolean};
const resultDefault:Result={placing:"Pending",score:"",verified:false};
const readValue=<T,>(key:string,fallback:T):T=>{if(typeof window==="undefined")return fallback;try{const value=JSON.parse(localStorage.getItem(key)||"null");return value??fallback}catch{return fallback}};
const readBouts=()=>{const value=readValue<unknown>("fighteye-live-bouts-v1",initialLiveBouts);return Array.isArray(value)&&value.every(item=>item&&typeof item==="object"&&typeof (item as LiveBout).id==="string")?value as LiveBout[]:initialLiveBouts};
const storeValue=(key:string,value:unknown)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
const downloadCsv=(filename:string,rows:string[][])=>{const csv=rows.map(row=>row.map(value=>'"'+value.replaceAll('"','""')+'"').join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};

export function LiveRingBoard({notice,openTimeline}:{notice:(message:string)=>void;openTimeline:()=>void}){
 const[bouts,setBouts]=useState<LiveBout[]>(readBouts);const[filter,setFilter]=useState<"All"|BoutStatus>("All");const[ring,setRing]=useState("All rings");const[query,setQuery]=useState("");const[watchedOnly,setWatchedOnly]=useState(false);const[alerts,setAlerts]=useState(()=>readValue("fighteye-live-alerts-v1",true));const[focusMode,setFocusMode]=useState(()=>readValue("fighteye-fight-day-focus-v1",false));const[online,setOnline]=useState(()=>typeof navigator==="undefined"||navigator.onLine);const[syncing,setSyncing]=useState(false);const[lastUpdated,setLastUpdated]=useState("Just now");const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const[linkedEvent]=useState(readActiveLiveEvent);
 useEffect(()=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>storeValue("fighteye-live-bouts-v1",bouts),100);return()=>{if(timer.current)clearTimeout(timer.current)}},[bouts]);
 useEffect(()=>storeValue("fighteye-live-alerts-v1",alerts),[alerts]);
 useEffect(()=>storeValue("fighteye-fight-day-focus-v1",focusMode),[focusMode]);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener("online",update);window.addEventListener("offline",update);return()=>{window.removeEventListener("online",update);window.removeEventListener("offline",update)}},[]);
 const enriched=useMemo(()=>bouts.map((bout,index)=>({...bout,boutNumber:bout.boutNumber??(Number(bout.id.replace(/\D/g,""))||index+1),delay:bout.delay??0,ready:bout.ready??false,watched:bout.watched??true})),[bouts]);const rings=["All rings",...Array.from(new Set(enriched.map(bout=>bout.ring))).sort()];const normalised=query.trim().toLowerCase();const visible=enriched.filter(bout=>(filter==="All"||bout.status===filter)&&(ring==="All rings"||bout.ring===ring)&&(!watchedOnly||bout.watched)&&(!normalised||[bout.athlete,bout.opponent,bout.category,bout.division,bout.ring,bout.id].join(" ").toLowerCase().includes(normalised))).sort((a,b)=>minutes(a.time)+(a.delay||0)-minutes(b.time)-(b.delay||0));const live=enriched.filter(bout=>bout.status==="Live").length;const calls=enriched.filter(bout=>bout.status==="Call").length;const delayed=enriched.filter(bout=>bout.status!=="Complete"&&(bout.delay||0)>=5).length;const next=enriched.filter(bout=>bout.status!=="Complete").sort((a,b)=>statusOrder.indexOf(b.status)-statusOrder.indexOf(a.status)||minutes(a.time)+(a.delay||0)-minutes(b.time)-(b.delay||0))[0];
 const update=(id:string,change:Partial<LiveBout>)=>setBouts(current=>current.map(bout=>bout.id===id?{...bout,...change}:bout));const advance=(id:string)=>setBouts(current=>current.map(bout=>{if(bout.id!==id)return bout;const nextStatus=statusOrder[Math.min(statusOrder.indexOf(bout.status)+1,statusOrder.length-1)];notice(bout.athlete+" moved to "+nextStatus);return{...bout,status:nextStatus}}));const back=(id:string)=>setBouts(current=>current.map(bout=>bout.id===id?{...bout,status:statusOrder[Math.max(0,statusOrder.indexOf(bout.status)-1)]}:bout));const refresh=()=>{setSyncing(true);setTimeout(()=>{setSyncing(false);setLastUpdated("Just now");notice("Live board refreshed")},650)};const adjusted=(bout:LiveBout)=>{const value=minutes(bout.time)+(bout.delay||0);return `${String(Math.floor(value/60)%24).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`};
 return <div className={"liveSuite enhancedTracker "+(focusMode?"focusMode":"")}>{linkedEvent&&<section className="active-live-event panel"><div><span className="badge gold">PHASE 103 · ACTIVE EVENT</span><h3>{linkedEvent.flag} {linkedEvent.name}</h3><p>{linkedEvent.start} · {linkedEvent.venue}, {linkedEvent.city}</p></div><button onClick={openTimeline}>View event timeline →</button></section>}<section className="liveHero trackerHero"><div><span className="badge gold">PHASE 87 · FIGHT DAY FOCUS</span><h2>See the next call before it becomes urgent.</h2><p>{linkedEvent?`Running ${linkedEvent.name} for the linked Prestige team.`:"Track every Prestige athlete, adjusted start time, ring delay and readiness action from one ringside view."}</p></div><div className="liveNow"><i className={online?"":"offline"}></i><span><b>{live||calls}</b> active calls</span><small>{online?lastUpdated+" · manual feed":"Offline · saved schedule"}</small></div></section><section className="fightDayBar panel"><div><i className={online?"online":"offline"}></i><span><b>{online?"Connected":"Working offline"}</b><small>{online?"Schedule available on this iPhone":"Changes stay on this device until reconnected"}</small></span></div><button className={focusMode?"active":""} onClick={()=>{setFocusMode(current=>!current);notice(focusMode?"Full live board restored":"Fight Day focus enabled")}}>{focusMode?"Show full board":"Enter Fight Day focus"}</button></section>
 <section className="nextFight panel"><div className="nextFightIdentity"><span className={"liveState "+(next?.status||"queued").toLowerCase()}>{next?.status==="Live"?"● LIVE":next?.status?.toUpperCase()||"CLEAR"}</span><small>NEXT TEAM PRIORITY</small><h2>{next?.athlete||"No open bouts"}</h2><p>{next?`${next.category} · ${next.division} · ${next.stage} vs ${next.opponent}`:"Every tracked bout is complete."}</p></div>{next&&<><div className="nextFightTime"><small>ADJUSTED CALL</small><b>{adjusted(next)}</b><span>{next.delay?`+${next.delay} min delay`:"On schedule"}</span></div><div className="nextFightRing"><small>LOCATION</small><b>{next.ring}</b><span>Bout {next.boutNumber}</span></div><button className={next.ready?"ready":""} onClick={()=>update(next.id,{ready:!next.ready})}>{next.ready?"✓ Athlete ready":"Mark athlete ready"}</button></>}</section>
 <section className="focusQueue">{enriched.filter(bout=>bout.status!=="Complete"&&bout.id!==next?.id).sort((a,b)=>minutes(a.time)+(a.delay||0)-minutes(b.time)-(b.delay||0)).slice(0,3).map((bout,index)=><button key={bout.id} onClick={()=>{setFocusMode(false);setQuery(bout.athlete)}}><small>{index===0?"AFTER NEXT":`${index+1} BOUTS AWAY`}</small><b>{bout.athlete}</b><span>{adjusted(bout)} · {bout.ring}</span></button>)}</section>
 <section className="liveMetrics"><article><small>Live now</small><b>{live}</b><span>On the mats</span></article><article><small>Call area</small><b>{calls}</b><span>Coach needed now</span></article><article><small>Delayed rings</small><b>{delayed}</b><span>Five minutes or more</span></article><article><small>Complete</small><b>{enriched.filter(bout=>bout.status==="Complete").length}/{bouts.length}</b><span>Results ready</span></article></section>
 <section className="ringPulse" aria-label="Ring status">{rings.slice(1).map(item=>{const ringBouts=enriched.filter(bout=>bout.ring===item&&bout.status!=="Complete"),delay=Math.max(0,...ringBouts.map(bout=>bout.delay||0));return <button className={ring===item?"active":""} key={item} onClick={()=>setRing(ring===item?"All rings":item)}><span>{item}</span><b>{ringBouts.length} open</b><small>{delay?`+${delay} min`:"On time"}</small></button>})}</section>
 <section className="trackerControls panel"><label className="trackerSearch">⌕<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search athlete, opponent or ring"/></label><select aria-label="Filter by ring" value={ring} onChange={event=>setRing(event.target.value)}>{rings.map(item=><option key={item}>{item}</option>)}</select><button className={watchedOnly?"active":""} onClick={()=>setWatchedOnly(current=>!current)}>★ Watched</button><button className={alerts?"alertsOn":""} onClick={()=>{setAlerts(current=>!current);notice(alerts?"Live alerts paused":"Live alerts enabled")}}>{alerts?"● Alerts on":"○ Alerts off"}</button><button className="refresh" disabled={syncing} onClick={refresh}>{syncing?"Refreshing…":"↻ Refresh"}</button></section>
 <section className="liveFilters statusFilters">{(["All","Live","Call","Queued","Complete"] as const).map(item=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item}<small>{item==="All"?enriched.length:enriched.filter(bout=>bout.status===item).length}</small></button>)}</section>
 <section className="ringBoard">{visible.map(bout=><article className={"ringBout trackerBout panel "+bout.status.toLowerCase()} key={bout.id}><div className="ringBoutTop"><span className={"liveState "+bout.status.toLowerCase()}>{bout.status==="Live"?"● LIVE":bout.status.toUpperCase()}</span><button className={bout.watched?"watch active":"watch"} aria-label={(bout.watched?"Unwatch ":"Watch ")+bout.athlete} onClick={()=>update(bout.id,{watched:!bout.watched})}>★</button><b>{adjusted(bout)}</b><strong>{bout.ring}</strong></div><div className="boutSchedule"><span>Bout {bout.boutNumber}</span><small>Scheduled {bout.time}</small><em className={(bout.delay||0)>=5?"late":""}>{bout.delay?`+${bout.delay} min`:"On time"}</em></div><div className="ringAthlete"><span>{bout.athlete.split(" ").map(part=>part[0]).join("")}</span><div><small>{bout.category} · {bout.division}</small><h3>{bout.athlete}</h3><p>vs {bout.opponent} · {bout.stage}</p></div></div><div className="trackerReadiness"><button className={bout.ready?"ready":""} onClick={()=>update(bout.id,{ready:!bout.ready})}>{bout.ready?"✓ Ready":"Athlete not ready"}</button><span><button aria-label={"Reduce delay for "+bout.athlete} onClick={()=>update(bout.id,{delay:Math.max(0,(bout.delay||0)-1)})}>−</button><b>{bout.delay||0}m delay</b><button aria-label={"Increase delay for "+bout.athlete} onClick={()=>update(bout.id,{delay:(bout.delay||0)+1})}>＋</button></span></div><div className="trackerActions"><button disabled={bout.status==="Queued"} onClick={()=>back(bout.id)}>← Back</button><button className="advance" disabled={bout.status==="Complete"} onClick={()=>advance(bout.id)}>{bout.status==="Queued"?"Move to call":bout.status==="Call"?"Start bout":bout.status==="Live"?"Mark complete":"Completed ✓"}</button></div></article>)}</section>{!visible.length&&<section className="panel trackerEmpty"><i>◎</i><h3>No fights match these filters</h3><p>Clear the search or choose All to see the full running order.</p><button onClick={()=>{setQuery("");setFilter("All");setRing("All rings");setWatchedOnly(false)}}>Clear filters</button></section>}</div>
}

export function CoachClashBoard({notice}:{notice:(message:string)=>void}){
 const[bouts]=useState<LiveBout[]>(readBouts);const[assignments,setAssignments]=useState<Record<string,string>>(()=>readValue("fighteye-coach-assignments-v1",initialAssignments));const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>storeValue("fighteye-coach-assignments-v1",assignments),100);return()=>{if(timer.current)clearTimeout(timer.current)}},[assignments]);
 const clashes=useMemo(()=>{const ids=new Set<string>();for(let i=0;i<bouts.length;i++)for(let j=i+1;j<bouts.length;j++){const a=bouts[i],b=bouts[j];if(a.status!=="Complete"&&b.status!=="Complete"&&assignments[a.id]===assignments[b.id]&&a.ring!==b.ring&&Math.abs(minutes(a.time)-minutes(b.time))<=15){ids.add(a.id);ids.add(b.id)}}return ids},[assignments,bouts]);
 const balance=()=>{const next={...assignments};const ordered=[...bouts].sort((a,b)=>minutes(a.time)-minutes(b.time));ordered.forEach((bout,index)=>{next[bout.id]=coaches[index%coaches.length]});setAssignments(next);notice("Coach cover auto-balanced")};
 return <div className="liveSuite"><section className="coachHero"><div><span className="badge gold">PHASE 49 · COACH ASSIGNMENT</span><h2>Stop ring clashes before they happen.</h2><p>Assign each Prestige bout, expose overlapping calls and rebalance coach cover in one tap.</p></div><div className={"clashCount "+(clashes.size?"danger":"clear")}><b>{clashes.size}</b><span>{clashes.size?"clashing bouts":"no clashes"}</span></div></section>
 <section className="coachToolbar panel"><div><b>{bouts.length} bouts</b><span> · {coaches.length} coaches · 15-minute clash window</span></div><button onClick={balance}>✦ Auto-balance cover</button></section>
 <section className="coachGrid">{bouts.map(bout=><article className={"coachAssignment panel "+(clashes.has(bout.id)?"hasClash":"")} key={bout.id}><div className="coachTime"><b>{bout.time}</b><span>{bout.ring}</span></div><div className="coachFight"><small>{bout.category} · {bout.stage}</small><h3>{bout.athlete}</h3><p>vs {bout.opponent}</p></div>{clashes.has(bout.id)&&<strong>! Coach clash</strong>}<label><span>Assigned coach</span><select value={assignments[bout.id]||coaches[0]} onChange={event=>setAssignments(current=>({...current,[bout.id]:event.target.value}))}>{coaches.map(coach=><option key={coach}>{coach}</option>)}</select></label></article>)}</section></div>
}

export function ResultsMedalCentre({notice}:{notice:(message:string)=>void}){
 const[bouts]=useState<LiveBout[]>(readBouts);const[results,setResults]=useState<Record<string,Result>>(()=>readValue("fighteye-results-v1",{}));const[filter,setFilter]=useState<"All"|"Medals"|"Unverified">("All");const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>storeValue("fighteye-results-v1",results),100);return()=>{if(timer.current)clearTimeout(timer.current)}},[results]);
 const update=(id:string,change:Partial<Result>)=>setResults(current=>({...current,[id]:{...(current[id]||resultDefault),...change}}));const value=(id:string)=>results[id]||resultDefault;const medals=["Gold","Silver","Bronze"] as const;const tally=medals.map(medal=>results?Object.values(results).filter(result=>result.placing===medal).length:0);const visible=bouts.filter(bout=>filter==="All"||filter==="Medals"&&medals.includes(value(bout.id).placing as typeof medals[number])||filter==="Unverified"&&!value(bout.id).verified);
 const exportResults=()=>{downloadCsv("prestige-results.csv",[["Bout","Athlete","Category","Opponent","Result","Score","Verified"],...bouts.map(bout=>[bout.id,bout.athlete,bout.category,bout.opponent,value(bout.id).placing,value(bout.id).score,value(bout.id).verified?"Yes":"No"])]);notice("Competition results exported")};
 return <div className="liveSuite"><section className="resultsHero"><div><span className="badge gold">PHASE 50 · RESULTS & MEDALS</span><h2>Capture the result while it is fresh.</h2><p>Record scores, verify outcomes and keep the Prestige medal table current from ringside.</p></div><div className="medalStack">{medals.map((medal,index)=><span className={medal.toLowerCase()} key={medal}><i>{["●","●","●"][index]}</i><b>{tally[index]}</b><small>{medal}</small></span>)}</div></section>
 <section className="resultMetrics"><article><small>Gold</small><b>{tally[0]}</b></article><article><small>Silver</small><b>{tally[1]}</b></article><article><small>Bronze</small><b>{tally[2]}</b></article><article><small>Verified</small><b>{Object.values(results).filter(result=>result.verified).length}/{bouts.length}</b></article></section>
 <section className="resultToolbar panel"><div>{(["All","Medals","Unverified"] as const).map(item=><button className={filter===item?"active":""} key={item} onClick={()=>setFilter(item)}>{item}</button>)}</div><button className="exportResults" onClick={exportResults}>⇩ Export results</button></section>
 <section className="resultList">{visible.map(bout=>{const result=value(bout.id);return <article className="resultCard panel" key={bout.id}><div className="resultIdentity"><span>{bout.athlete.split(" ").map(part=>part[0]).join("")}</span><div><small>{bout.id} · {bout.category} · {bout.stage}</small><h3>{bout.athlete}</h3><p>vs {bout.opponent}</p></div></div><div className="resultInputs"><label>Outcome<select value={result.placing} onChange={event=>update(bout.id,{placing:event.target.value as Result["placing"]})}>{["Pending","Gold","Silver","Bronze","Win","Loss"].map(item=><option key={item}>{item}</option>)}</select></label><label>Score<input value={result.score} onChange={event=>update(bout.id,{score:event.target.value})} placeholder="e.g. 10–7"/></label></div><button className={result.verified?"verified":""} onClick={()=>{update(bout.id,{verified:!result.verified});notice(result.verified?"Result returned to review":"Result verified")}}>{result.verified?"✓ Verified":"Verify result"}</button></article>})}</section></div>
}
