"use client";

import {useEffect,useMemo,useState} from "react";

type Task={id:string;athlete:string;area:string;estimatedTime:string;officialTime:string;status:string;coach:string;warmupStart:string;equipment:boolean;conflict?:boolean;division:string};
type ClubAthlete={id:string;name:string;area:string;time:string;status:string;division:string;result?:string};
type Snapshot={id:string;time:string;title:string;detail:string;type:string;source:string};
async function getJson<T>(path:string,fallback:T):Promise<T>{try{const response=await fetch(path,{headers:{accept:"application/json"}});if(!response.ok)throw new Error("Unavailable");return await response.json() as T}catch{return fallback}}

const coachFallback={updatedAt:new Date().toISOString(),coaches:[{name:"Will Taylor",status:"busy",availableAt:"10:52",athletes:["Charlie Baxter","Jamie Granville"]},{name:"Trevor",status:"available",availableAt:"Now",athletes:["Olivia Green"]}],tasks:[{id:"ct1",athlete:"Charlie Baxter",area:"Ring 2",estimatedTime:"10:48",officialTime:"10:42",status:"called",coach:"Will Taylor",warmupStart:"10:25",equipment:true,conflict:true,division:"Older Cadet -42kg PF"},{id:"ct2",athlete:"Jamie Granville",area:"Ring 4",estimatedTime:"10:54",officialTime:"10:50",status:"warm-up",coach:"Will Taylor",warmupStart:"10:34",equipment:true,conflict:true,division:"Junior LC"},{id:"ct3",athlete:"Olivia Green",area:"Ring 1",estimatedTime:"11:12",officialTime:"11:05",status:"on-deck",coach:"Trevor",warmupStart:"10:50",equipment:false,division:"Cadet PF"}]};
const clubFallback={club:"Prestige Martial Arts",updatedAt:new Date().toISOString(),summary:{athletes:8,live:1,warming:2,waiting:3,finished:2},medals:{gold:2,silver:1,bronze:3},athletes:[{id:"cm1",name:"Charlie Baxter",area:"Ring 2",time:"10:48",status:"called",division:"Older Cadet -42kg PF"},{id:"cm2",name:"Jamie Granville",area:"Ring 4",time:"10:54",status:"warm-up",division:"Junior LC"},{id:"cm3",name:"Olivia Green",area:"Ring 1",time:"11:12",status:"on-deck",division:"Cadet PF"},{id:"cm4",name:"Luke Walsh",area:"Ring 3",time:"11:25",status:"waiting",division:"Senior Male -63kg PF"},{id:"cm5",name:"Hollie Haworth",area:"Ring 5",time:"10:10",status:"finished",division:"Cadet PF",result:"Gold"}]};
const replayFallback={event:"ICO World Championships",updatedAt:new Date().toISOString(),snapshots:[{id:"rp1",time:"09:30",title:"Charlie checked in",detail:"Registration confirmed",type:"athlete",source:"Verified manual"},{id:"rp2",time:"10:02",title:"Ring 2 delayed",detail:"+6 minutes",type:"delay",source:"Sportdata"},{id:"rp3",time:"10:18",title:"Quarter-final bracket updated",detail:"Opponent confirmed",type:"bracket",source:"Sportdata"},{id:"rp4",time:"10:44",title:"Gold medal confirmed",detail:"Club medal table updated",type:"result",source:"Verified organiser"}],report:{bouts:18,wins:12,losses:6,golds:3,silvers:2,bronzes:4,peakDelay:14,confidence:96}};

export function CoachCommandMobile({notice}:{notice:(message:string)=>void}){
 const[data,setData]=useState(coachFallback);const[busy,setBusy]=useState(false);const conflicts=useMemo(()=>data.tasks.filter((task:Task)=>task.conflict),[data]);
 const refresh=async()=>{setBusy(true);setData(await getJson("/api/live-operations/coach-command",coachFallback));setBusy(false);notice("Coach command updated")};useEffect(()=>{void getJson("/api/live-operations/coach-command",coachFallback).then(setData)},[]);
 return <section className="phone-workspace"><div className="phone-workspace-head"><div><span className="badge gold">PHASE 40 · COACH COMMAND</span><h2>Coach the next athlete, not the whole spreadsheet.</h2><p>Warm-up windows, assignments, equipment and clashes prioritised for phone use.</p></div><button onClick={refresh}>{busy?"Updating…":"↻ Refresh"}</button></div><div className="phone-kpis"><article><small>Due in 20 min</small><b>{data.tasks.length}</b></article><article><small>Conflicts</small><b>{conflicts.length}</b></article><article><small>Equipment alerts</small><b>{data.tasks.filter((task:Task)=>!task.equipment).length}</b></article></div><section className="phone-stack">{data.tasks.map((task:Task,index:number)=><article className={`coach-task ${task.conflict?"conflict":""}`} key={task.id}><div className="coach-task-time"><small>{index===0?"NOW":"NEXT"}</small><b>{task.estimatedTime}</b><span>{task.officialTime} official</span></div><div className="coach-task-main"><span className="mobile-status-pill">{task.status}</span><h3>{task.athlete}</h3><p>{task.division}</p><div className="coach-task-meta"><b>{task.area}</b><span>Warm-up {task.warmupStart}</span><span>Coach: {task.coach}</span></div>{task.conflict&&<em>Coach clash detected</em>}{!task.equipment&&<em className="warn-text">Equipment check incomplete</em>}</div><div className="coach-task-actions"><button onClick={()=>notice(`${task.athlete} profile opened`)}>Open athlete</button><button onClick={()=>notice(task.conflict?"Reassignment workflow opened":"Brief marked ready")}>{task.conflict?"Reassign":"Brief"}</button></div></article>)}</section><section className="panel phone-panel"><div className="panelHead"><div><span className="eyebrow">COACH AVAILABILITY</span><h3>Live team cover</h3></div></div>{data.coaches.map(coach=><div className="enterprise-control-row" key={coach.name}><div><b>{coach.name}</b><small>{coach.athletes.join(" · ")||"No current athletes"}</small></div><span className={coach.status==="available"?"ok":"warn"}>{coach.status} · {coach.availableAt}</span></div>)}</section></section>
}

export function ClubMissionBoard({notice}:{notice:(message:string)=>void}){
 const[data,setData]=useState(clubFallback);const[filter,setFilter]=useState("active");useEffect(()=>{void getJson("/api/live-operations/club-mission",clubFallback).then(setData)},[]);const list=data.athletes.filter((athlete:ClubAthlete)=>filter==="all"||(filter==="active"?athlete.status!=="finished":athlete.status===filter));
 return <section className="phone-workspace"><div className="phone-workspace-head"><div><span className="badge gold">PHASE 41 · CLUB MISSION</span><h2>{data.club}</h2><p>Every athlete, ring and medal in one phone view.</p></div><div className="medal-badge">🥇 {data.medals.gold} · 🥈 {data.medals.silver} · 🥉 {data.medals.bronze}</div></div><section className="mission-summary"><article><b>{data.summary.live}</b><small>Live</small></article><article><b>{data.summary.warming}</b><small>Warm-up</small></article><article><b>{data.summary.waiting}</b><small>Waiting</small></article><article><b>{data.summary.finished}</b><small>Finished</small></article></section><div className="mobile-filter-row">{["active","warm-up","finished","all"].map(value=><button className={filter===value?"active":""} onClick={()=>setFilter(value)} key={value}>{value}</button>)}</div><section className="mission-athletes">{list.map((athlete:ClubAthlete)=><article key={athlete.id} className={`mission-athlete ${athlete.status}`}><time>{athlete.time}</time><div><span>{athlete.area} · {athlete.status}</span><h3>{athlete.name}</h3><small>{athlete.division}</small>{athlete.result&&<b className="mission-result">{athlete.result}</b>}</div><button onClick={()=>notice(`${athlete.name} opened`)}>Open</button></article>)}</section><section className="panel phone-panel"><span className="eyebrow">MEDAL RACE</span><h3>Club performance</h3><div className="medal-race-bars">{([["Gold",data.medals.gold],["Silver",data.medals.silver],["Bronze",data.medals.bronze]] as [string,number][]).map(([label,total])=><div key={label}><span>{label}</span><b style={{width:`${Math.min(100,total*20)}%`}}/><strong>{total}</strong></div>)}</div></section></section>
}

export function MobileEventReplay({notice}:{notice:(message:string)=>void}){
 const[data,setData]=useState(replayFallback);const[active,setActive]=useState(3);useEffect(()=>{void getJson("/api/live-operations/mobile-replay",replayFallback).then(setData)},[]);const snapshot:Snapshot=data.snapshots[Math.min(active,data.snapshots.length-1)];
 const exportReport=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="fighteye-event-report.json";anchor.click();URL.revokeObjectURL(url);notice("Event report exported")};
 return <section className="phone-workspace"><div className="phone-workspace-head"><div><span className="badge gold">PHASE 42 · REPLAY & SHARE</span><h2>Replay the event day.</h2><p>See schedule, bracket and result changes in order, then export a shareable report.</p></div><button onClick={exportReport}>Export</button></div><section className="replay-focus"><small>{snapshot.time}</small><h2>{snapshot.title}</h2><p>{snapshot.detail}</p><span>{snapshot.source}</span></section><input aria-label="Replay timeline" className="replay-range" type="range" min="0" max={Math.max(0,data.snapshots.length-1)} value={active} onChange={event=>setActive(Number(event.target.value))}/><section className="replay-timeline">{data.snapshots.map((item:Snapshot,index:number)=><button className={index===active?"active":""} key={item.id} onClick={()=>setActive(index)}><time>{item.time}</time><div><b>{item.title}</b><small>{item.detail}</small></div><span>{item.type}</span></button>)}</section><section className="phone-report-grid"><article><small>Bouts</small><b>{data.report.bouts}</b></article><article><small>Wins</small><b>{data.report.wins}</b></article><article><small>Golds</small><b>{data.report.golds}</b></article><article><small>Peak delay</small><b>{data.report.peakDelay}m</b></article><article><small>Data confidence</small><b>{data.report.confidence}%</b></article></section></section>
}
