export type DateStatus="Verified"|"Provisional"|"Corrected";
export type ResultStatus="Complete"|"Partial"|"Missing"|"Not due";
export type EventRecord={id:string;name:string;org:string;country:string;flag:string;city:string;venue:string;start:string;end:string;closing?:string;collections:string[];disciplines:string[];level:"UK"|"Europe"|"World"|"USA";sourceName:string;sourceUrl:string;registrationUrl:string;verified:boolean;dateStatus?:DateStatus;dateNote?:string;resultStatus?:ResultStatus;resultsUrl?:string};

const sportdata="https://www.sportdata.org/kickboxing/event_list_prod/events.html";
const kihapp="https://www.kihapp.com/arts/12-kickboxing/tournaments";

export const eventCatalogue:EventRecord[]=[
 {id:"wako-youth-worlds-2026",name:"WAKO Children, Cadet & Junior World Championships",org:"WAKO",country:"Italy",flag:"🇮🇹",city:"Jesolo",venue:"Palazzo del Turismo",start:"2026-09-18",end:"2026-09-27",closing:"2026-08-20",collections:["Featured","Youth","World championships"],disciplines:["PF","LC","KL","FC","K1"],level:"World",sourceName:"WAKO",sourceUrl:"https://www.wako.sport/event-details/wako-world-championship-all-disciplines-for-children-cadets-and-juniors",registrationUrl:sportdata,verified:true},
 {id:"ipon-open-2026",name:"IPON Open",org:"IPON",country:"United Kingdom",flag:"🇬🇧",city:"United Kingdom",venue:"See organiser listing",start:"2026-09-27",end:"2026-09-27",closing:"2026-09-18",collections:["UK","Open circuit"],disciplines:["PF","LC","KL"],level:"UK",sourceName:"Kihapp",sourceUrl:kihapp,registrationUrl:kihapp,verified:false},
 {id:"diamond-nationals-2026",name:"Diamond National Championships",org:"NASKA / Sport Karate",country:"United States",flag:"🇺🇸",city:"Minneapolis",venue:"See organiser listing",start:"2026-10-01",end:"2026-10-03",collections:["USA","Sport Karate"],disciplines:["Points","Continuous","Forms"],level:"USA",sourceName:"NASKA",sourceUrl:"https://naska.com/2026-calendar/",registrationUrl:"https://naska.com/2026-calendar/",verified:true},
 {id:"norwegian-cup-2026",name:"Top Ten Norwegian Cup",org:"WAKO",country:"Norway",flag:"🇳🇴",city:"Bergen",venue:"Zinken Hopp",start:"2026-10-02",end:"2026-10-04",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"sana-open-2026",name:"SANA Open 2026",org:"WAKO",country:"Bosnia and Herzegovina",flag:"🇧🇦",city:"Sarajevo",venue:"See Sportdata",start:"2026-10-03",end:"2026-10-03",closing:"2026-09-20",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"lithuania-open-2026",name:"Lithuania Open 2026",org:"WAKO",country:"Lithuania",flag:"🇱🇹",city:"See Sportdata",venue:"See Sportdata",start:"2026-10-03",end:"2026-10-04",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"wkc-leeds-2026",name:"WKC Leeds",org:"WKC / Sport Karate",country:"United Kingdom",flag:"🇬🇧",city:"Leeds",venue:"See organiser listing",start:"2026-10-06",end:"2026-10-06",closing:"2026-09-25",collections:["UK","Sport Karate"],disciplines:["PF","LC","KL"],level:"UK",sourceName:"Kihapp",sourceUrl:kihapp,registrationUrl:kihapp,verified:false},
 {id:"czech-open-2026",name:"Czech Open 2026",org:"WAKO",country:"Czech Republic",flag:"🇨🇿",city:"Prague",venue:"See Sportdata",start:"2026-10-09",end:"2026-10-10",closing:"2026-09-25",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"celtic-open-2026",name:"The Celtic Open 2026",org:"WAKO",country:"Ireland",flag:"🇮🇪",city:"See Sportdata",venue:"See Sportdata",start:"2026-10-11",end:"2026-10-11",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"uzbekistan-world-cup-2026",name:"Uzbekistan Kickboxing World Cup",org:"WAKO",country:"Uzbekistan",flag:"🇺🇿",city:"Tashkent",venue:"Navoiy shoh ko'chasi 30",start:"2026-10-13",end:"2026-10-18",closing:"2026-09-20",collections:["Featured","World Cup"],disciplines:["PF","LC","KL","FC","K1"],level:"World",sourceName:"WAKO",sourceUrl:"https://www.wako.sport/event-details/uzbekistan-kickboxing-world-cup-2026",registrationUrl:sportdata,verified:true},
 {id:"ico-worlds-2026",name:"ICO World Championships",org:"ICO",country:"France",flag:"🇫🇷",city:"Thonon-les-Bains",venue:"See organiser pack",start:"2026-10-14",end:"2026-10-18",closing:"2026-09-20",collections:["Featured","World championships"],disciplines:["PF","LC","KL","K1"],level:"World",sourceName:"ICO / USKA",sourceUrl:"https://www.uskakickboxing.co.uk/forthcomingevents",registrationUrl:"https://www.uskakickboxing.co.uk/forthcomingevents",verified:false},
 {id:"wartburg-classics-2026",name:"Adidas Wartburg Classics 2026",org:"WAKO",country:"Germany",flag:"🇩🇪",city:"Bad Salzungen",venue:"See Sportdata",start:"2026-10-16",end:"2026-10-17",closing:"2026-10-01",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"bristol-open-2026",name:"The Bristol Open 2026",org:"WAKO GB",country:"United Kingdom",flag:"🇬🇧",city:"Bristol",venue:"Chellaram Sports Ground",start:"2026-10-23",end:"2026-10-25",closing:"2026-10-05",collections:["Featured","UK","Open circuit"],disciplines:["PF","LC","KL"],level:"UK",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"balkan-open-2026",name:"20th Balkan Open 2026",org:"WAKO",country:"Bosnia and Herzegovina",flag:"🇧🇦",city:"Tešanj",venue:"See Sportdata",start:"2026-10-24",end:"2026-10-24",closing:"2026-10-10",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"slovenia-open-2026",name:"40th Slovenia Open 2026",org:"WAKO",country:"Slovenia",flag:"🇸🇮",city:"Zagorje ob Savi",venue:"See Sportdata",start:"2026-10-24",end:"2026-10-24",closing:"2026-10-10",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"pointfighting-grand-prix-2026",name:"Pointfighting Grand Prix 2026",org:"WAKO",country:"Poland",flag:"🇵🇱",city:"See Sportdata",venue:"See Sportdata",start:"2026-10-24",end:"2026-10-25",collections:["Europe","Point fighting"],disciplines:["PF"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"iska-ama-worlds-2026",name:"ISKA AMA World Championships",org:"ISKA",country:"Spain",flag:"🇪🇸",city:"Madrid",venue:"Aranjuez competition venue",start:"2026-11-05",end:"2026-11-08",closing:"2026-10-15",collections:["Featured","World championships"],disciplines:["PF","LC","KL","K1"],level:"World",sourceName:"ISKA",sourceUrl:"https://www.iskaworldhq.com/events/",registrationUrl:"https://www.iskaworldhq.com/events/",verified:false},
 {id:"pan-american-2026",name:"Pan-American International",org:"NASKA / Sport Karate",country:"United States",flag:"🇺🇸",city:"Miami",venue:"See organiser listing",start:"2026-11-06",end:"2026-11-07",collections:["USA","Sport Karate"],disciplines:["Points","Continuous","Forms"],level:"USA",sourceName:"NASKA",sourceUrl:"https://naska.com/2026-calendar/",registrationUrl:"https://naska.com/2026-calendar/",verified:true},
 {id:"wako-europeans-2026",name:"WAKO European Championships 2026",org:"WAKO",country:"North Macedonia",flag:"🇲🇰",city:"Skopje",venue:"See Sportdata",start:"2026-11-06",end:"2026-11-15",closing:"2026-10-10",collections:["Featured","European championships"],disciplines:["PF","LC","KL","FC","K1"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"peterborough-3-2026",name:"Peterborough Championship Series No. 3",org:"Peterborough Series",country:"United Kingdom",flag:"🇬🇧",city:"Kettering",venue:"Kettering Leisure Village",start:"2026-11-08",end:"2026-11-08",closing:"2026-10-30",collections:["UK","Series"],disciplines:["PF","LC","KL"],level:"UK",sourceName:"Fighting Falcons",sourceUrl:"https://www.fighting-falcons.co.uk/Events%20Calendar/",registrationUrl:"https://www.fighting-falcons.co.uk/Events%20Calendar/",verified:false},
 {id:"westfalen-open-2026",name:"Westfalen Open Cup 2026",org:"WAKO",country:"Germany",flag:"🇩🇪",city:"See Sportdata",venue:"See Sportdata",start:"2026-11-14",end:"2026-11-14",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"ico-legacy-cup-2026",name:"ICO Legacy Cup – Novices",org:"ICO",country:"United Kingdom",flag:"🇬🇧",city:"Rugby",venue:"Benn Hall",start:"2026-11-15",end:"2026-11-15",closing:"2026-11-05",collections:["UK","Development"],disciplines:["PF","LC","KL"],level:"UK",sourceName:"Kihapp",sourceUrl:kihapp,registrationUrl:kihapp,verified:false},
 {id:"senshi-christmas-cup-2026",name:"Senshi Christmas Cup 2026",org:"WAKO",country:"Denmark",flag:"🇩🇰",city:"See Sportdata",venue:"See Sportdata",start:"2026-11-21",end:"2026-11-21",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"kutina-open-2026",name:"27th International Kutina Open",org:"WAKO",country:"Croatia",flag:"🇭🇷",city:"Kutina",venue:"See Sportdata",start:"2026-11-21",end:"2026-11-21",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"swedish-open-2026",name:"Swedish Open 2026",org:"WAKO",country:"Sweden",flag:"🇸🇪",city:"See Sportdata",venue:"See Sportdata",start:"2026-11-28",end:"2026-11-28",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"asian-championships-2026",name:"Asian Kickboxing Championships 2026",org:"WAKO",country:"Cambodia",flag:"🇰🇭",city:"See Sportdata",venue:"See Sportdata",start:"2026-12-11",end:"2026-12-21",collections:["Featured","Asian championships"],disciplines:["PF","LC","KL","FC","K1"],level:"World",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"danish-open-2027",name:"Danish Open 2027",org:"WAKO",country:"Denmark",flag:"🇩🇰",city:"See Sportdata",venue:"See Sportdata",start:"2027-02-05",end:"2027-02-06",collections:["Europe","Open circuit"],disciplines:["PF","LC","KL"],level:"Europe",sourceName:"Sportdata",sourceUrl:sportdata,registrationUrl:sportdata,verified:true},
 {id:"hungarian-world-cup-2026",name:"31st Hungarian Kickboxing World Cup",org:"WAKO",country:"Hungary",flag:"🇭🇺",city:"Budapest",venue:"BOK Sports Hall",start:"2026-06-12",end:"2026-06-15",collections:["World Cup","Europe"],disciplines:["PF","LC","KL"],level:"World",sourceName:"WAKO",sourceUrl:"https://www.wako.sport/events",registrationUrl:sportdata,verified:true,dateStatus:"Verified",resultStatus:"Complete",resultsUrl:"https://www.wako.sport/official-results"},
 {id:"wku-worlds-2026",name:"WKU World Championships",org:"WKU",country:"Germany",flag:"🇩🇪",city:"Berlin",venue:"Estrel Berlin",start:"2026-08-03",end:"2026-08-09",collections:["World championships"],disciplines:["PF","LC","KL","K1"],level:"World",sourceName:"WKU",sourceUrl:"https://www.wkuworld.com/events/",registrationUrl:"https://www.wkuworld.com/events/",verified:true,dateStatus:"Corrected",dateNote:"Location corrected from Abu Dhabi to Berlin after checking the official WKU event information.",resultStatus:"Missing"},
 {id:"wako-gb-nationals-2026",name:"Kickboxing GB National Championships",org:"WAKO GB",country:"United Kingdom",flag:"🇬🇧",city:"Barnsley",venue:"Barnsley Metrodome",start:"2026-04-18",end:"2026-04-19",collections:["UK","National championships"],disciplines:["PF","LC","KL"],level:"UK",sourceName:"Sportdata",sourceUrl:"https://www.sportdata.org/kickboxing/event_list_prod/events.html",registrationUrl:"https://kickboxinggb.com/events/",verified:true,dateStatus:"Corrected",dateNote:"Location corrected from Nottingham to Barnsley Metrodome; the 18–19 April dates were confirmed by Sportdata.",resultStatus:"Partial",resultsUrl:"https://setopen.sportdata.org/wakogbranking/ranking_information_main.php"},
 {id:"gb-grand-slam-2-2026",name:"GB Grand Slam – K2 Crawley 2026",org:"WAKO GB",country:"United Kingdom",flag:"🇬🇧",city:"Crawley",venue:"K2 Crawley",start:"2026-07-11",end:"2026-07-12",collections:["UK","GB Grand Slam"],disciplines:["PF","LC","KL"],level:"UK",sourceName:"Sportdata",sourceUrl:"https://www.sportdata.org/kickboxing/sportsid/calendar_main.php?active_menu=calendar&count=60&dir=up&sort=datum",registrationUrl:"https://kickboxinggb.com/events/",verified:true,dateStatus:"Corrected",dateNote:"Date and location corrected from 26–27 April in Birmingham to 11–12 July at K2 Crawley.",resultStatus:"Partial",resultsUrl:"https://www.sportdata.org/kickboxing/set-online/calendar_archiv_main.php?active_menu=calendar&count=0&dir=down&sort=datum"}
];

export const catalogueVerifiedAt="17 September 2026";
