"use client";

import {FormEvent,useState} from "react";
import "./injury-tracker.css";

const key="fighteye-club-injuries-v1";
type Injury={id:string;athleteId:string;date:string;area:string;note:string;reviewDate:string;status:"Active"|"Modified training"|"Awaiting review"|"Cleared"};
type Envelope={schema:"fighteye-injuries-encrypted-v1";salt:string;iv:string;data:string};
const encode=(bytes:Uint8Array)=>btoa(Array.from(bytes,b=>String.fromCharCode(b)).join(""));
const decode=(value:string)=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
async function derive(passphrase:string,salt:Uint8Array){const material=await crypto.subtle.importKey("raw",new TextEncoder().encode(passphrase),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt:Uint8Array.from(salt),iterations:250000,hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
async function encrypt(rows:Injury[],passphrase:string,salt:Uint8Array):Promise<Envelope>{const iv=crypto.getRandomValues(new Uint8Array(12));const secret=await derive(passphrase,salt);const encrypted=await crypto.subtle.encrypt({name:"AES-GCM",iv:Uint8Array.from(iv)},secret,new TextEncoder().encode(JSON.stringify(rows)));return{schema:"fighteye-injuries-encrypted-v1",salt:encode(salt),iv:encode(iv),data:encode(new Uint8Array(encrypted))}}
async function decrypt(record:Envelope,passphrase:string):Promise<Injury[]>{if(record.schema!=="fighteye-injuries-encrypted-v1")throw new Error("Invalid tracker");const salt=decode(record.salt),iv=decode(record.iv);if(salt.length!==16||iv.length!==12)throw new Error("Invalid tracker");const secret=await derive(passphrase,salt);const rows=JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:Uint8Array.from(iv)},secret,Uint8Array.from(decode(record.data)))));if(!Array.isArray(rows)||rows.length>5000)throw new Error("Invalid tracker");return rows}

export default function InjuryTracker({athlete,onClose}:{athlete:{id:string;name:string};onClose:()=>void}){
 const[passphrase,setPassphrase]=useState("");const[salt,setSalt]=useState<Uint8Array|null>(null);const[rows,setRows]=useState<Injury[]>([]);const[error,setError]=useState("");const[stored]=useState(()=>typeof window!=="undefined"&&!!localStorage.getItem(key));
 const unlocked=!!salt;
 async function unlock(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");try{if(!crypto.subtle)throw new Error("Secure storage is unavailable on this device.");const saved=localStorage.getItem(key);if(saved){const record=JSON.parse(saved) as Envelope;setRows(await decrypt(record,passphrase));setSalt(decode(record.salt))}else{if(passphrase.length<12)throw new Error("Use at least 12 characters.");const nextSalt=crypto.getRandomValues(new Uint8Array(16));localStorage.setItem(key,JSON.stringify(await encrypt([],passphrase,nextSalt)));setRows([]);setSalt(nextSalt)}}catch{setError("Could not unlock the tracker. Check the passphrase and secure connection.")}}
 async function save(next:Injury[]){if(!salt)return;try{const record=await encrypt(next,passphrase,salt);localStorage.setItem(key,JSON.stringify(record));setRows(next);setError("")}catch{setError("Could not save this record on this device.")}}
 function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=new FormData(form),date=String(values.get("date")||""),area=String(values.get("area")||"").trim().slice(0,80),note=String(values.get("note")||"").trim().slice(0,500),reviewDate=String(values.get("reviewDate")||"");if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!area||reviewDate&&reviewDate<date)return;save([...rows,{id:crypto.randomUUID(),athleteId:athlete.id,date,area,note,reviewDate,status:"Active"}]);form.reset()}
 const visible=rows.filter(row=>row.athleteId===athlete.id).sort((a,b)=>b.date.localeCompare(a.date));
 return <div className="injury-backdrop" onClick={onClose}><section className="injury-sheet" role="dialog" aria-modal="true" aria-label={`Private injury tracker for ${athlete.name}`} onClick={event=>event.stopPropagation()}><header><div><small>PRIVATE · THIS DEVICE ONLY</small><h2>{athlete.name} · injury tracker</h2></div><button type="button" onClick={onClose} aria-label="Close injury tracker">×</button></header><p>Records are encrypted on this device and are not included in profile exports. Keep the passphrase safe: it cannot be recovered. A follow-up date does not clear a fighter to train or compete.</p>{!unlocked?<form onSubmit={unlock}><label>{stored?"Unlock tracker":"Create tracker passphrase (12+ characters)"}<input type="password" required minLength={stored?1:12} value={passphrase} onChange={event=>setPassphrase(event.target.value)} autoComplete="off"/></label><button className="primary">{stored?"Unlock":"Create private tracker"}</button></form>:<><form onSubmit={add} className="injury-form"><label>Date noted<input name="date" type="date" defaultValue={new Date().toLocaleDateString("en-CA",{timeZone:"Europe/London"})} required/></label><label>Area / injury<input name="area" maxLength={80} required/></label><label className="wide">Brief note<textarea name="note" maxLength={500} rows={3}/></label><label>Follow-up date<input name="reviewDate" type="date"/></label><button className="primary">Save record</button></form><div className="injury-records">{visible.length?visible.map(row=><article key={row.id}><strong>{row.area}</strong><small>{row.date}{row.reviewDate?` · Follow-up ${row.reviewDate}`:""}</small><p>{row.note||"No further note"}</p><label>Status<select value={row.status} onChange={event=>save(rows.map(item=>item.id===row.id?{...item,status:event.target.value as Injury["status"]}:item))}>{["Active","Modified training","Awaiting review","Cleared"].map(value=><option key={value}>{value}</option>)}</select></label><button type="button" onClick={()=>{if(window.confirm("Delete this injury record from this device?"))save(rows.filter(item=>item.id!==row.id))}}>Delete record</button></article>):<p>No injury records for this fighter.</p>}</div></>}{error&&<p role="alert" className="injury-error">{error}</p>}</section></div>
}
