"use client";

import {useEffect,useState} from "react";

type CheckIn={technique:number;confidence:number;fitness:number;note:string};
type Progress=Record<string,CheckIn>;
type Load={sessions:number;intensity:number;soreness:number;available:boolean;note:string};
type Loads=Record<string,Load>;
type Checklist={selected:boolean;weight:boolean;consent:boolean;entry:boolean};
type Squad=Record<string,Checklist>;

const athletes=["Charlie Baxter","Olivia Green","Hollie Haworth","Jamie Granville"];
const defaults:Loads={"Charlie Baxter":{sessions:4,intensity:4,soreness:2,available:true,note:""},"Olivia Green":{sessions:3,intensity:3,soreness:1,available:true,note:""},"Hollie Haworth":{sessions:4,intensity:3,soreness:3,available:true,note:""},"Jamie Granville":{sessions:5,intensity:4,soreness:2,available:true,note:""}};
const initials=(name:string)=>name.split(" ").map(part=>part[0]).join("");
const read=<T,>(key:string,fallback:T):T=>{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)||"null")??fallback}catch{return fallback}};
function useSaved<T>(key:string,fallback:T){const[state,setState]=useState<T>(()=>read(key,fallback));useEffect(()=>{const timer=setTimeout(()=>{try{localStorage.setItem(key,JSON.stringify(state))}catch{}},100);return()=>clearTimeout(timer)},[key,state]);return[state,setState] as const}
const progressScore=(progress:Progress,name:string)=>{const item=progress[name]||{technique:3,confidence:3,fitness:3,note:""};return Math.round((item.technique+item.confidence+item.fitness)/15*100)};
const loadScore=(item:Load)=>Math.min(100,Math.round(item.sessions*9+item.intensity*8+item.soreness*7));

export function ActionCentre({notice}:{notice:(message:string)=>void}){
 const[done,setDone]=useSaved<Record<string,boolean>>("fighteye-action-centre-v1",{});const[filter,setFilter]=useState<"Open"|"Urgent"|"All">("Open");const tasks=[{id:"review-charlie",athlete:"Charlie Baxter",title:"Review first-exchange footage",due:"Today",priority:"Urgent"},{id:"weight-hollie",athlete:"Hollie Haworth",title:"Confirm competition weight trend",due:"Tomorrow",priority:"Urgent"},{id:"plan-olivia",athlete:"Olivia Green",title:"Update measurable training target",due:"This week",priority:"Normal"},{id:"check-jamie",athlete:"Jamie Granville",title:"Complete weekly readiness check-in",due:"This week",priority:"Normal"},{id:"entries-team",athlete:"Whole team",title:"Check consent and entry readiness",due:"Before selection",priority:"Normal"}];const visible=tasks.filter(task=>(filter==="All"||(filter==="Open"&&!done[task.id])||(filter==="Urgent"&&task.priority==="Urgent"&&!done[task.id])));const open=tasks.filter(task=>!done[task.id]).length;
 return <div className="opsPath"><OpsHero phase="56" label="ACTION CENTRE" title="One clear list of what needs attention." text="Bring coaching, athlete and competition actions together in priority order." metric={open.toString()} metricLabel="open actions"/><section className="opsMetrics"><Metric label="Open actions" value={open} detail="Across the pathway"/><Metric label="Urgent" value={tasks.filter(task=>task.priority==="Urgent"&&!done[task.id]).length} detail="Due within 48 hours"/><Metric label="Completed" value={tasks.length-open} detail="This planning cycle"/><Metric label="Owners" value="3 coaches" detail="Shared accountability"/></section><section className="actionToolbar panel"><div>{(["Open","Urgent","All"] as const).map(option=><button className={filter===option?"active":""} key={option} onClick={()=>setFilter(option)}>{option}</button>)}</div><span>{visible.length} shown</span></section><section className="actionList">{visible.map(task=><article className={"panel actionItem "+(done[task.id]?"done":"")} key={task.id}><button aria-label={(done[task.id]?"Reopen ":"Complete ")+task.title} onClick={()=>setDone(current=>({...current,[task.id]:!current[task.id]}))}>{done[task.id]?"✓":""}</button><div><small>{task.athlete}</small><h3>{task.title}</h3></div><span className={task.priority==="Urgent"?"urgent":""}>{task.due}</span></article>)}</section><section className="panel opsFooter"><div><span className="eyebrow">DAILY COACH VIEW</span><h3>{open?open+" actions remain":"All actions complete"}</h3><p>Completed actions remain available under All.</p></div><button className="primary" onClick={()=>notice("Action summary shared with coaches")}>Share action summary</button></section></div>;
}

export function LoadMonitor({notice}:{notice:(message:string)=>void}){
 const[loads,setLoads]=useSaved<Loads>("fighteye-athlete-load-v1",defaults);const update=(name:string,change:Partial<Load>)=>setLoads(current=>({...current,[name]:{...(current[name]||defaults[name]),...change}}));const available=athletes.filter(name=>(loads[name]||defaults[name]).available).length;const high=athletes.filter(name=>loadScore(loads[name]||defaults[name])>=75).length;
 return <div className="opsPath"><OpsHero phase="57" label="LOAD & AVAILABILITY" title="Keep athletes ready without overloading them." text="Record weekly volume, intensity, soreness and availability before squad selection." metric={available+"/"+athletes.length} metricLabel="available athletes"/><section className="opsMetrics"><Metric label="Available" value={available} detail="For squad selection"/><Metric label="High load" value={high} detail="Coach review needed"/><Metric label="Average sessions" value={(athletes.reduce((sum,name)=>sum+(loads[name]||defaults[name]).sessions,0)/athletes.length).toFixed(1)} detail="This week"/><Metric label="Check-in status" value="Current" detail="Saved on this device"/></section><section className="loadGrid">{athletes.map(name=>{const item=loads[name]||defaults[name],score=loadScore(item),risk=score>=75?"High":score>=55?"Managed":"Fresh";return <article className="panel loadCard" key={name}><div className="loadHead"><i>{initials(name)}</i><div><small>WEEKLY LOAD</small><h3>{name}</h3></div><button className={item.available?"available":"unavailable"} onClick={()=>update(name,{available:!item.available})}>{item.available?"Available":"Unavailable"}</button></div><label><span>Sessions <b>{item.sessions}</b></span><input type="range" min="0" max="7" value={item.sessions} onChange={event=>update(name,{sessions:Number(event.target.value)})}/></label><label><span>Intensity <b>{item.intensity}/5</b></span><input type="range" min="1" max="5" value={item.intensity} onChange={event=>update(name,{intensity:Number(event.target.value)})}/></label><label><span>Soreness <b>{item.soreness}/5</b></span><input type="range" min="1" max="5" value={item.soreness} onChange={event=>update(name,{soreness:Number(event.target.value)})}/></label><div className={"loadGauge "+risk.toLowerCase()}><span style={{width:score+"%"}}/><b>{risk} · {score}% load</b></div><label className="loadNote">Coach note<input value={item.note} onChange={event=>update(name,{note:event.target.value})} placeholder="Restriction, recovery or availability note"/></label></article>})}</section><section className="panel opsFooter"><div><span className="eyebrow">WEEKLY LOAD CONTROL</span><h3>{high?high+" athletes need load review":"Team load is controlled"}</h3><p>Availability and load feed directly into Phase 58.</p></div><button className="primary" onClick={()=>notice("Athlete load check-in confirmed")}>Confirm load check-in</button></section></div>;
}

const emptyChecklist=():Checklist=>({selected:false,weight:false,consent:false,entry:false});
export function SquadSelection({notice}:{notice:(message:string)=>void}){
 const[loads]=useSaved<Loads>("fighteye-athlete-load-v1",defaults);const[progress]=useSaved<Progress>("fighteye-progress-tracking-v1",{});const[squad,setSquad]=useSaved<Squad>("fighteye-squad-selection-v1",{});const[event,setEvent]=useState("Peterborough Series");const update=(name:string,change:Partial<Checklist>)=>setSquad(current=>({...current,[name]:{...(current[name]||emptyChecklist()),...change}}));const selected=athletes.filter(name=>(squad[name]||emptyChecklist()).selected).length;const cleared=athletes.filter(name=>{const item=squad[name]||emptyChecklist();return item.weight&&item.consent&&item.entry}).length;
 return <div className="opsPath"><OpsHero phase="58" label="SQUAD SELECTION" title="Select the right athletes with clear evidence." text="Combine readiness, availability, load and entry checks before confirming a competition squad." metric={selected.toString()} metricLabel="athletes selected"/><section className="selectionEvent panel"><label>Competition<select value={event} onChange={eventChange=>setEvent(eventChange.target.value)}><option>Peterborough Series</option><option>Autumn Open</option><option>Winter Cup</option><option>English Open</option></select></label><div><small>SELECTION STATUS</small><b>{selected} selected · {cleared} entry-ready</b></div><button onClick={()=>notice("Selection rationale exported")}>Export rationale</button></section><section className="selectionGrid">{athletes.map(name=>{const load=loads[name]||defaults[name],checks=squad[name]||emptyChecklist(),ready=progressScore(progress,name),loadValue=loadScore(load),recommended=load.available&&ready>=60&&loadValue<85;return <article className={"panel selectionCard "+(checks.selected?"selected":"")} key={name}><div className="selectionHead"><i>{initials(name)}</i><div><small>{recommended?"RECOMMENDED":"COACH REVIEW"}</small><h3>{name}</h3></div><button onClick={()=>update(name,{selected:!checks.selected})}>{checks.selected?"✓ Selected":"Select"}</button></div><div className="selectionSignals"><span><small>Readiness</small><b>{ready}%</b></span><span><small>Load</small><b>{loadValue}%</b></span><span><small>Available</small><b>{load.available?"Yes":"No"}</b></span></div><div className="selectionChecks">{(["weight","consent","entry"] as const).map(key=><button className={checks[key]?"checked":""} key={key} onClick={()=>update(name,{[key]:!checks[key]})}><i>{checks[key]?"✓":""}</i><span>{key==="weight"?"Weight confirmed":key==="consent"?"Consent current":"Entry details ready"}</span></button>)}</div></article>})}</section><section className="panel opsFooter"><div><span className="eyebrow">FINAL APPROVAL</span><h3>{selected?selected+" athletes selected for "+event:"Build the competition squad"}</h3><p>Selection remains provisional until all entry checks are complete.</p></div><button className="primary" disabled={!selected} onClick={()=>notice("Competition squad approved")}>Approve squad</button></section></div>;
}

function OpsHero({phase,label,title,text,metric,metricLabel}:{phase:string;label:string;title:string;text:string;metric:string;metricLabel:string}){return <section className="opsHero"><div><span className="badge gold">PHASE {phase} · {label}</span><h2>{title}</h2><p>{text}</p></div><aside><b>{metric}</b><span>{metricLabel}</span></aside></section>}
function Metric({label,value,detail}:{label:string;value:string|number;detail:string}){return <article><small>{label}</small><b>{value}</b><span>{detail}</span></article>}
