"use client";

import {useEffect,useRef,useState} from "react";
import {initialLiveBouts} from "./competition-live-data";

type Result={placing:"Pending"|"Gold"|"Silver"|"Bronze"|"Win"|"Loss";score:string;verified:boolean};
type AthleteReview={rating:number;strength:string;development:string;action:string;complete:boolean};
type ReviewState={athletes:Record<string,AthleteReview>;highlight:string;priority:string;published:boolean};
const blankReview:AthleteReview={rating:3,strength:"",development:"",action:"",complete:false};
const blankState:ReviewState={athletes:{},highlight:"",priority:"",published:false};
const readJson=<T,>(key:string,fallback:T):T=>{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)||"null")??fallback}catch{return fallback}};
const athletes=Array.from(new Set(initialLiveBouts.map(bout=>bout.athlete)));

export default function PostEventReview({notice,openDevelopment}:{notice:(message:string)=>void;openDevelopment:()=>void}){
 const[results]=useState<Record<string,Result>>(()=>readJson("fighteye-results-v1",{}));const[review,setReview]=useState<ReviewState>(()=>readJson("fighteye-post-event-review-v1",blankState));const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{try{localStorage.setItem("fighteye-post-event-review-v1",JSON.stringify(review))}catch{}},120);return()=>{if(timer.current)clearTimeout(timer.current)}},[review]);
 const recorded=Object.values(results).filter(result=>result.placing!=="Pending");const medals=["Gold","Silver","Bronze"] as const;const medalTotal=recorded.filter(result=>medals.includes(result.placing as typeof medals[number])).length;const verified=recorded.filter(result=>result.verified).length;const wins=recorded.filter(result=>["Gold","Win"].includes(result.placing)).length;const decided=recorded.filter(result=>["Gold","Win","Loss"].includes(result.placing)).length;
 const athleteResult=(name:string)=>{const bouts=initialLiveBouts.filter(bout=>bout.athlete===name);const values=bouts.map(bout=>results[bout.id]).filter(Boolean);return{bouts,values,medals:values.filter(value=>medals.includes(value.placing as typeof medals[number])).length,verified:values.filter(value=>value.verified).length}};
 const updateAthlete=(name:string,change:Partial<AthleteReview>)=>setReview(current=>({...current,published:false,athletes:{...current.athletes,[name]:{...(current.athletes[name]||blankReview),...change}}}));const value=(name:string)=>review.athletes[name]||blankReview;
 const actionComplete=athletes.filter(name=>value(name).complete).length;
 const summary=["Prestige Martial Arts · Post-event review",recorded.length+" results recorded · "+medalTotal+" medals · "+verified+" verified","Highlight: "+(review.highlight||"Not recorded"),"Club priority: "+(review.priority||"Not recorded"),...athletes.map(name=>{const item=value(name);return name+" · "+item.rating+"/5 · Action: "+(item.action||"Not set")})].join("\n");
 const share=async()=>{try{if(navigator.share)await navigator.share({title:"FightEye post-event review",text:summary});else{await navigator.clipboard.writeText(summary);notice("Review summary copied")}}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;notice("Could not share the review")}};
 return <div className="postReview"><section className="reviewHero"><div><span className="badge gold">PHASE 52 · POST-EVENT REVIEW</span><h2>Turn every result into the next improvement.</h2><p>Bring verified outcomes, coach observations and athlete actions together before the next training cycle begins.</p></div><div className={"reviewStatus "+(review.published?"published":"draft")}><b>{review.published?"Published":"Draft"}</b><span>{actionComplete}/{athletes.length} actions complete</span></div></section>
 <section className="reviewMetrics"><article><small>Results recorded</small><b>{recorded.length}</b><span>{verified} verified</span></article><article><small>Medals</small><b>{medalTotal}</b><span>{medals.map(medal=>recorded.filter(result=>result.placing===medal).length).join(" · ")||"0 · 0 · 0"} G · S · B</span></article><article><small>Decided win rate</small><b>{decided?Math.round(wins/decided*100):0}%</b><span>{wins} wins from {decided}</span></article><article><small>Development actions</small><b>{actionComplete}/{athletes.length}</b><span>Coach follow-up</span></article></section>
 <section className="reviewNarrative"><article className="panel"><label><span>Competition highlight</span><textarea value={review.highlight} onChange={event=>setReview(current=>({...current,highlight:event.target.value,published:false}))} placeholder="What did the team do particularly well?"/></label></article><article className="panel"><label><span>Priority for the next training block</span><textarea value={review.priority} onChange={event=>setReview(current=>({...current,priority:event.target.value,published:false}))} placeholder="What must improve before the next competition?"/></label></article></section>
 <section className="reviewAthletes">{athletes.map(name=>{const data=athleteResult(name),item=value(name);return <article className="reviewAthlete panel" key={name}><div className="reviewAthleteHead"><span>{name.split(" ").map(part=>part[0]).join("")}</span><div><small>{data.bouts.map(bout=>bout.category).join(" · ")} · {data.medals} medals</small><h3>{name}</h3><p>{data.values.length} results · {data.verified} verified</p></div><strong className={item.complete?"done":"open"}>{item.complete?"✓ Action complete":"Action open"}</strong></div><div className="ratingRow"><span>Competition performance</span><div>{[1,2,3,4,5].map(score=><button aria-label={score+" out of 5"} aria-pressed={item.rating===score} className={item.rating>=score?"active":""} key={score} onClick={()=>updateAthlete(name,{rating:score})}>★</button>)}</div><b>{item.rating}/5</b></div><div className="reviewFields"><label>Strength shown<textarea value={item.strength} onChange={event=>updateAthlete(name,{strength:event.target.value})} placeholder="Technique, mindset or tactical success"/></label><label>Development focus<textarea value={item.development} onChange={event=>updateAthlete(name,{development:event.target.value})} placeholder="One clear priority for training"/></label><label className="wide">Next coaching action<input value={item.action} onChange={event=>updateAthlete(name,{action:event.target.value})} placeholder="e.g. Review first-exchange footage on Tuesday"/></label></div><button className={item.complete?"completeAction":""} onClick={()=>updateAthlete(name,{complete:!item.complete})}>{item.complete?"↺ Reopen action":"✓ Mark action complete"}</button></article>})}</section>
 <section className="panel reviewActions"><div><span className="eyebrow">REVIEW CONTROL</span><h3>{review.published?"Review published":"Complete, share and publish"}</h3><p>{recorded.length?"The report uses the latest saved competition results.":"No outcomes have been recorded yet; the coaching review can still be prepared as a draft."}</p></div><div><button onClick={share}>Share summary</button><button onClick={()=>window.print()}>Print review</button><button onClick={openDevelopment}>Create development plans</button><button className="primary" onClick={()=>{setReview(current=>({...current,published:true}));notice("Post-event review published")}}>{review.published?"Republish":"Publish review"}</button></div></section></div>
}
