"use client";
import {useState} from "react";
const Badge=({children,tone=""}:{children:React.ReactNode,tone?:string})=><span className={`badge ${tone}`}>{children}</span>;
const fighters=[
 {name:"Charlie Baxter",cats:"PF / LC / KL · OC −42 kg",next:"Area 4 · Fight 18",eta:"22 min",state:"Ready"},
 {name:"Jamie Granville",cats:"K1 · Junior −60 kg",next:"Ring 1 · Fight 9",eta:"41 min",state:"Checked in"},
 {name:"Hollie Haworth",cats:"PF · OC −50 kg",next:"Area 2 · Fight 24",eta:"56 min",state:"Warm-up"},
 {name:"Olivia Green",cats:"LC · YC −37 kg",next:"Area 6 · Fight 31",eta:"1 h 14",state:"Checked in"},
];
const areas=[
 {name:"Area 1",discipline:"PF",fight:"OC −47 kg · Quarter-final",running:"On time",delay:0},
 {name:"Area 2",discipline:"PF",fight:"OC −50 kg · Last 16",running:"+8 min",delay:8},
 {name:"Area 3",discipline:"LC",fight:"YC −42 kg · Semi-final",running:"On time",delay:0},
 {name:"Area 4",discipline:"PF",fight:"OC −42 kg · Last 16",running:"+3 min",delay:3},
 {name:"Area 5",discipline:"KL",fight:"Junior −60 kg · Quarter-final",running:"Paused",delay:14},
 {name:"Ring 1",discipline:"K1",fight:"Junior −60 kg · Bout 7",running:"On time",delay:0},
];
export default function CompetitionDay({notice}:{notice:(x:string)=>void}){const[tab,setTab]=useState("Control room"),[follow,setFollow]=useState(true);return <><section className="listHead"><div><span className="eyebrow">PHASE 13 · LIVE COMPETITION OPERATIONS</span><h2>Competition-day command</h2><p>One live view of areas, running orders, team readiness and verified results.</p></div><Badge tone="green">LIVE · 13:48</Badge></section>
<section className="eventStrip"><div><Badge tone="gold">WAKO</Badge><span><h2>GB Grand Slam 3</h2><p>National Indoor Arena · 11 October 2026</p></span></div><div>{[["6","Areas live"],["142","Fights complete"],["38","Remaining"],["94%","On schedule"]].map(x=><span key={x[1]}><b>{x[0]}</b><small>{x[1]}</small></span>)}</div></section>
<div className="profileTabs">{["Control room","My fight team","Running order","Check-in","Results desk"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
{tab==="Control room"&&<><section className="liveAreas">{areas.map(a=><article className={`panel liveArea ${a.delay>10?"late":""}`} key={a.name}><div><Badge>{a.discipline}</Badge><Badge tone={a.delay===0?"green":"gold"}>{a.running}</Badge></div><h3>{a.name}</h3><p>{a.fight}</p><div className="areaProgress"><i><em style={{width:(70-a.delay)+"%"}}/></i><small>{a.delay===0?"Fight 24 of 31":"Schedule adjusted"}</small></div><button onClick={()=>notice(`${a.name} running order opened`)}>Open area →</button></article>)}</section><section className="controlGrid"><article className="panel"><span className="eyebrow">LIVE EXCEPTIONS</span><h3>Needs attention</h3>{[["Area 5 paused","Equipment check in progress","14 min"],["Fighter not at marshalling","Ethan Clarke · Area 2","8 min"],["Result requires verification","Fight FE-261011-0141","2 min"]].map(x=><button className="liveException" onClick={()=>notice(`${x[0]} opened`)} key={x[0]}><i>!</i><span><b>{x[0]}</b><small>{x[1]}</small></span><em>{x[2]}</em></button>)}</article><article className="panel"><span className="eyebrow">ANNOUNCEMENTS</span><h3>Event broadcast</h3>{[["13:43","Area 5 temporarily paused"],["13:36","LC categories moved to Area 3"],["13:28","Older Cadet PF call to warm-up"]].map(x=><div className="broadcast" key={x[0]}><i>{x[0]}</i><span>{x[1]}</span></div>)}<button className="primary" onClick={()=>notice("Announcement composer opened")}>＋ New announcement</button></article></section></>}
{tab==="My fight team"&&<section className="teamDayGrid"><article className="panel"><div className="panelHead"><div><span className="eyebrow">PRESTIGE MARTIAL ARTS</span><h3>Today’s fighters</h3></div><button className={follow?"following":""} onClick={()=>{setFollow(!follow);notice(follow?"Team alerts paused":"Team alerts enabled")}}>{follow?"● Alerts on":"○ Alerts off"}</button></div>{fighters.map((f,i)=><div className="dayFighter" key={f.name}><i>{f.name.split(" ").map(x=>x[0]).join("")}</i><span><b>{f.name}</b><small>{f.cats}</small><em>{f.next}</em></span><strong>{f.eta}</strong><Badge tone={i===0?"gold":"green"}>{f.state}</Badge><button onClick={()=>notice(`${f.name} live card opened`)}>Open</button></div>)}</article><aside className="panel nextCall"><Badge tone="gold">NEXT CALL</Badge><h2>Charlie Baxter</h2><p>Area 4 · PF Older Cadet −42 kg</p><div><b>22</b><small>estimated minutes</small></div>{[["Equipment","Complete"],["Coach","Will Taylor"],["Marshalling","In 12 min"],["Opponent","Máté Horváth"]].map(x=><span key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></span>)}<button className="primary" onClick={()=>notice("Charlie marked ready for marshalling")}>Mark ready</button></aside></section>}
{tab==="Running order"&&<section className="runningBoard"><div className="runFilters"><select><option>All areas</option>{areas.map(a=><option key={a.name}>{a.name}</option>)}</select><button className="active">Now</button><button>Next 30 min</button><button>My team</button></div><article className="panel runTable"><div className="runHead"><span>Order</span><span>Area</span><span>Category</span><span>Match-up</span><span>Estimate</span><span>Status</span></div>{[["LIVE","Area 4","PF · OC −42 kg","Ethan Clarke vs Noah Williams","Now","Live"],["18","Area 4","PF · OC −42 kg","Charlie Baxter vs Máté Horváth","14:10","Called"],["19","Area 4","PF · OC −42 kg","Leo Martin vs Adam Jones","14:17","Scheduled"],["24","Area 2","PF · OC −50 kg","Hollie Haworth vs Eva Novak","14:44","Scheduled"],["31","Area 6","LC · YC −37 kg","Olivia Green vs Mia Brown","15:02","Scheduled"]].map(x=><div key={x[0]}><strong>{x[0]}</strong><b>{x[1]}</b><span>{x[2]}</span><span><b>{x[3]}</b></span><em>{x[4]}</em><Badge tone={x[5]==="Live"?"green":x[5]==="Called"?"gold":""}>{x[5]}</Badge></div>)}</article></section>}
{tab==="Check-in"&&<section className="checkinGrid"><article className="panel"><span className="eyebrow">CLUB CHECK-IN</span><h3>Prestige Martial Arts</h3>{fighters.map((f,i)=><div className="checkRow" key={f.name}><button className={i<3?"checked":""} onClick={()=>notice(`${f.name} check-in updated`)}>{i<3?"✓":""}</button><span><b>{f.name}</b><small>{f.cats}</small></span><Badge tone={i<3?"green":"gold"}>{i<3?"Complete":"Missing"}</Badge></div>)}</article><article className="panel"><span className="eyebrow">READINESS CHECKLIST</span><h3>Charlie Baxter</h3>{["Registration confirmed","Licence and eligibility valid","Weigh-in accepted · 40.8 kg","Guardian consent valid","Required equipment checked","Coach accreditation active"].map(x=><div className="complianceTick" key={x}>✓ {x}</div>)}<button className="primary" onClick={()=>notice("Digital check-in pass prepared")}>Show check-in pass</button></article></section>}
{tab==="Results desk"&&<section className="resultsDesk"><article className="panel"><span className="eyebrow">RECENT RESULTS</span><h3>Awaiting confirmation</h3>{[["FE-261011-0141","Area 2","Noah Williams vs Ethan Clarke","11–9","Official feed"],["FE-261011-0140","Area 3","Olivia Green vs Mia Brown","2–1","Judge cards"],["FE-261011-0139","Ring 1","Jamie Granville vs Leo Martin","R2 TKO","Supervisor"]].map(x=><div className="resultReview" key={x[0]}><code>{x[0]}</code><span><b>{x[2]}</b><small>{x[1]} · {x[4]}</small></span><strong>{x[3]}</strong><button onClick={()=>notice(`${x[0]} verification opened`)}>Verify</button></div>)}</article><aside className="panel"><Badge tone="green">SOURCE PROTECTED</Badge><h3>Result reconciliation</h3><p>Official area submissions are compared with imported brackets, judge cards and FightEye video evidence. Conflicts never overwrite a verified result silently.</p>{[["Confirmed today","139"],["Needs review","3"],["Disputed","0"],["Median confirmation","2m 11s"]].map(x=><div className="resultStat" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</aside></section>}</>}
