"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import ProcessingView from "./processing-view";
import AthleteProfiles from "./athlete-profiles";
import VerificationExtras from "./verification-extras";
import MatchupIntelligence from "./matchup-intelligence";
import CoachingAnalysis from "./coaching-analysis";
import PlatformSync from "./platform-sync";
import ConsentCentre from "./consent-centre";
import RuleAwareAnalysis from "./rule-aware-analysis";
import YouTubeSources from "./youtube-sources";
import TrainingHealth from "./training-health";
import RankingsScouting from "./rankings-scouting";
import FederationPlatform from "./federation-platform";
import OperationsCentre from "./operations-centre";
import CompetitionDay from "./competition-day";
import MobileExperience from "./mobile-experience";
import {CoachCommandMobile,ClubMissionBoard,MobileEventReplay} from "./enterprise-mobile";
import CompetitionDiscovery from "./competition-discovery";
import EntryReadiness from "./entry-readiness";
import CompetitionOperations from "./competition-operations";
import {CoachClashBoard,LiveRingBoard,ResultsMedalCentre} from "./competition-live-suite";
import PostEventReview from "./post-event-review";
import {DevelopmentPlans,ProgressTracking,SeasonPlanner} from "./development-pathway";
import {ActionCentre,LoadMonitor,SquadSelection} from "./operations-pathway";
import {EventLaunch,LogisticsBudget} from "./event-readiness";
import {EventCloseout,TeamBriefing,TeamItinerary} from "./event-execution";
type View="overview"|"competitionDay"|"mobile"|"coachCommand"|"clubMission"|"eventReplay"|"federationPlatform"|"operations"|"processing"|"profiles"|"matchups"|"coaching"|"analysis"|"youtube"|"training"|"rankings"|"sync"|"consent"|"athletes"|"competitions"|"entryPlanner"|"eventPack"|"liveSchedule"|"coachClashes"|"resultsCentre"|"postReview"|"developmentPlans"|"progressTracking"|"seasonPlanner"|"actionCentre"|"loadMonitor"|"squadSelection"|"logisticsBudget"|"eventLaunch"|"teamItinerary"|"teamBriefing"|"eventCloseout"|"fights"|"rules"|"duplicates"|"permissions"|"audit";
type Federation="WAKO"|"ISKA"|"ICO"|"WKKC"|"WKU"; type Discipline="PF"|"LC"|"KL"|"K1"|"K2";
const federationSources:Record<Federation,{version:string,url:string,note:string}>={WAKO:{version:"Current rules portal",url:"https://www.wako.sport/rules-overview",note:"Official WAKO rules portal"},ISKA:{version:"Jurisdiction dependent",url:"https://www.iskaworldhq.com/rules/",note:"ISKA states that rules may vary by jurisdiction"},ICO:{version:"Published discipline files",url:"https://ico-martialarts.com/",note:"Confirm against the event-issued ICO rules pack"},WKKC:{version:"Event verification required",url:"https://www.wkcworld.com/",note:"Stored as WKKC; source availability varies by event"},WKU:{version:"Updated 20 June 2022",url:"https://www.wkuworld.com/organisation/rules/rules-english/",note:"Official WKU English rules page"}};
const scoring:Record<Discipline,string[]>={PF:["Punch · 1 point","Body kick · 1 point","Head kick · 2 points","Jump body kick · 2 points","Jump head kick · 3 points","Foot sweep · 1 point"],LC:["Clean punch · 1 score","Body kick · 1 score","Head kick · 2 scores","Jump body kick · 2 scores","Jump head kick · 3 scores","Continuous judges’ total"],KL:["Clean punch · 1 score","Body kick · 1 score","Thigh kick · 1 score","Head kick · 2 scores","Controlled contact required","Continuous judges’ total"],K1:["Legal punch, kick or knee · judged","Effective legal techniques score","Damage, dominance and activity considered","Limited clinch; no elbows","Full-contact ring rules"],K2:["No verified official category named K2","Do not apply K1 rules automatically","Map to K1 only after organiser confirmation"]};
const exceptions:Partial<Record<Federation,Partial<Record<Discipline,string[]>>>>={ISKA:{PF:["Often named Semi Contact; confirm event variant"],K1:["May be K-1 Light Kick at amateur events; confirm contact level"]},ICO:{K1:["ICO publishes K1 Continuous rules; venue format may be mat or ring"]},WKKC:{PF:["Confirm whether the event uses WKC/WKKC point rules"],LC:["Verify the current event pack before officiating"]},WKU:{LC:["Judges also evaluate technique, defence, combinations and initiative"],KL:["Low kicks distinguish Kick-Light from Light Contact"]}};
const athletes=[{id:"ATH-1042",name:"Charlie Baxter",club:"Prestige Martial Arts",nation:"GB",grade:"Black belt",record:"18–7",status:"Verified"},{id:"ATH-1043",name:"Noah Williams",club:"Elite Combat Academy",nation:"GB",grade:"Black belt",record:"14–9",status:"Verified"},{id:"ATH-1044",name:"Máté Horváth",club:"Halker-Király Team",nation:"HU",grade:"Advanced",record:"22–8",status:"Review"},{id:"ATH-1045",name:"Jamie Granville",club:"Prestige Martial Arts",nation:"GB",grade:"Black belt",record:"11–4",status:"Verified"}];
const bouts=[{id:"FE-260612-0182",event:"Hungarian World Cup",cat:"PF",division:"Older Cadet −42 kg",match:"Charlie Baxter vs Máté Horváth",result:"10–7",source:"Official",verify:"Verified",video:true},{id:"FE-260427-0041",event:"GB Grand Slam 2",cat:"LC",division:"Older Cadet −42 kg",match:"Charlie Baxter vs Noah Williams",result:"1–2",source:"Imported",verify:"Verified",video:true},{id:"FE-260418-0094",event:"WAKO GB Nationals",cat:"KL",division:"Older Cadet −42 kg",match:"Charlie Baxter vs Ethan Clarke",result:"3–0",source:"Manual",verify:"Verified",video:false},{id:"FE-260329-0027",event:"Peterborough Series",cat:"PF",division:"Older Cadet −42 kg",match:"Charlie Baxter vs Noah Williams",result:"12–9",source:"Video suggestion",verify:"Review",video:true},{id:"FE-260309-0118",event:"WKU English Open",cat:"K1",division:"Junior −60 kg",match:"Jamie Granville vs Leo Martin",result:"3–0",source:"Official",verify:"Verified",video:true}];
const audits=[["02:44","Dean Baxter","Verified fight","FE-260612-0182"],["02:39","FightEye Import","Created competition","Hungarian World Cup"],["02:27","Dean Baxter","Updated athlete club","ATH-1042"],["Yesterday","Video Intelligence","Flagged possible duplicate","ATH-1044 / ATH-0971"],["Yesterday","Saf Taylor","Uploaded fight video","FE-260427-0041"]];
const Badge=({children,tone=""}:{children:React.ReactNode,tone?:string})=><span className={"badge "+tone}>{children}</span>;
export default function Home(){
 const[view,setView]=useState<View>("overview"),[query,setQuery]=useState(""),[cat,setCat]=useState("All"),[federation,setFederation]=useState<Federation>("WAKO"),[discipline,setDiscipline]=useState<Discipline>("PF"),[modal,setModal]=useState<null|"athlete"|"club"|"competition"|"role"|"video">(null),[mobileMore,setMobileMore]=useState(false),[toast,setToast]=useState(""),[busy,setBusy]=useState(false),[dupes,setDupes]=useState([{id:1,a:"Máté Horváth",b:"Mate Horvath",type:"Athlete",score:96,reasons:"Name, birth year and club match"},{id:2,a:"Prestige Martial Arts",b:"Prestige MA Nottingham",type:"Club",score:88,reasons:"Name, city and contact match"},{id:3,a:"GB Grand Slam 2 · Bout 41",b:"Imported bout #0041",type:"Fight",score:92,reasons:"Athletes, category and score match"}]);const file=useRef<HTMLInputElement>(null);const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const workspaceRef=useRef<HTMLElement>(null);
 const filtered=useMemo(()=>bouts.filter(b=>(cat==="All"||b.cat===cat)&&Object.values(b).join(" ").toLowerCase().includes(query.toLowerCase())),[cat,query]);
 useEffect(()=>{if(!mobileMore)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setMobileMore(false)};window.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close)}},[mobileMore]);
 useEffect(()=>()=>{if(toastTimer.current)clearTimeout(toastTimer.current)},[]);
 function notice(x:string){if(toastTimer.current)clearTimeout(toastTimer.current);setToast(x);toastTimer.current=setTimeout(()=>setToast(""),2600)}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=new FormData(e.currentTarget);const body=Object.fromEntries(form);try{const res=await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,entity:modal})});const data=await res.json();if(!res.ok)throw new Error(data.error);notice(`${modal} record saved with audit entry`);setModal(null)}catch(err){notice(err instanceof Error?err.message:"Could not save record")}finally{setBusy(false)}}
 async function upload(f?:File){if(!f)return;setBusy(true);const data=new FormData();data.set("file",f);try{const res=await fetch("/api/videos",{method:"POST",body:data});const out=await res.json();if(!res.ok)throw new Error(out.error);const duration=await new Promise<number>(resolve=>{const v=document.createElement("video");v.preload="metadata";v.onloadedmetadata=()=>{URL.revokeObjectURL(v.src);resolve(Number.isFinite(v.duration)?v.duration:0)};v.onerror=()=>resolve(0);v.src=URL.createObjectURL(f)});await fetch("/api/analysis",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({videoId:out.video.id,filename:f.name,durationSeconds:duration})});notice("Video stored and analysis queued for review");setModal(null);setView("processing")}catch(err){notice(err instanceof Error?err.message:"Upload failed")}finally{setBusy(false)}}
 const nav:[View,string,string][]=[["overview","Command centre","⌂"],["competitionDay","Competition day","●"],["mobile","Mobile experience","▯"],["coachCommand","Coach command","♙"],["clubMission","Club mission","◆"],["eventReplay","Event replay","↻"],["federationPlatform","Federation platform","◆"],["operations","Operations centre","◫"],["processing","Verification centre","◉"],["profiles","Athlete profiles","◈"],["matchups","Match-up intelligence","◇"],["coaching","Video coaching lab","▶"],["analysis","Strengths & weaknesses","✦"],["youtube","YouTube sources","▶"],["training","Training & health","♥"],["rankings","Rankings & scouting","△"],["sync","Platform sync","↯"],["consent","Media & consent","▣"],["athletes","Athletes","◎"],["competitions","Competitions","◇"],["entryPlanner","Entry planner","✓"],["eventPack","Event pack","▦"],["liveSchedule","Live ring board","●"],["coachClashes","Coach clashes","♙"],["resultsCentre","Results & medals","★"],["postReview","Post-event review","↗"],["developmentPlans","Development plans","◫"],["progressTracking","Progress tracking","↗"],["seasonPlanner","Season planner","△"],["actionCentre","Action centre","✓"],["loadMonitor","Load & availability","♥"],["squadSelection","Squad selection","◎"],["logisticsBudget","Logistics & budget","£"],["eventLaunch","Event launch","✓"],["teamItinerary","Team itinerary","◷"],["teamBriefing","Team briefing","✉"],["eventCloseout","Event closeout","✓"],["fights","Fight database","⚔"],["rules","Scoring rules","▤"],["duplicates","Duplicate review","⊞"],["permissions","Access roles","♙"],["audit","Audit history","↻"]];
 const recordViews:View[]=["competitions","permissions","athletes","fights","processing","coaching"];
 const mobilePrimary:[View,string,string][]=[["overview","Home","⌂"],["competitions","Events","◇"],["liveSchedule","Live","●"],["clubMission","Team","◆"]];
 const pathwayViews:[View,string,string][]=[["postReview","Review","52"],["developmentPlans","Plan","53"],["progressTracking","Progress","54"],["seasonPlanner","Season","55"],["actionCentre","Actions","56"],["loadMonitor","Load","57"],["squadSelection","Select","58"],["logisticsBudget","Logistics","59"],["eventLaunch","Launch","60"],["teamItinerary","Itinerary","61"],["teamBriefing","Briefing","62"],["eventCloseout","Closeout","63"]];
 const openView=(next:View)=>{setView(next);setMobileMore(false);workspaceRef.current?.scrollTo({top:0,behavior:"auto"});window.scrollTo({top:0,behavior:"auto"})};
 return <main className="app"><aside className="rail"><div className="brand"><i>FE</i><span><b>FightEye</b><small>Enterprise 11.2</small></span></div><div className="phase"><Badge tone="gold">PHASE 63</Badge><p>Competition cycle</p></div><nav>{nav.map(n=><button key={n[0]} className={view===n[0]?"active":""} onClick={()=>setView(n[0])}><i>{n[2]}</i>{n[1]}{n[0]==="liveSchedule"&&<em>LIVE</em>}{n[0]==="processing"&&<em>2</em>}</button>)}</nav><div className="storage"><b>System status</b><p><span className="dot"/>Fight database</p><p><span className="dot"/>Live event feed</p><p><span className="dot"/>Mobile sync</p></div><div className="user"><i>DB</i><span><b>Dean Baxter</b><small>System administrator</small></span></div></aside>
 <section className="workspace" ref={workspaceRef}><header><div><span className="eyebrow">FIGHTEYE / ENTERPRISE</span><h1>{nav.find(n=>n[0]===view)?.[1]}</h1></div><div className="headActions"><button className="icon" aria-label="Search">⌕</button>{recordViews.includes(view)&&<button className="primary" onClick={()=>setModal(view==="competitions"?"competition":view==="permissions"?"role":view==="athletes"?"athlete":"video")}>＋ Add {view==="competitions"?"competition":view==="permissions"?"role":view==="athletes"?"athlete":"record"}</button>}</div></header>
 {pathwayViews.some(item=>item[0]===view)&&<nav className="pathwayQuickNav" aria-label="Athlete development pathway">{pathwayViews.map(item=><button key={item[0]} className={view===item[0]?"active":""} onClick={()=>openView(item[0])}><b>{item[2]}</b>{item[1]}</button>)}</nav>}
 {view==="overview"&&<><section className="hero"><div><Badge tone="green">FOUNDATION ACTIVE</Badge><h2>One source of truth<br/><em>for every fight.</em></h2><p>Structured records, private video metadata, verification provenance and a complete change history—ready for FightEye’s intelligence phases.</p></div><div className="health"><span><b>12</b>linked tables</span><span><b>4</b>disciplines</span><span><b>100%</b>audited writes</span></div></section><section className="stats">{[["248","Fight records","18 this month"],["92","Athletes","31 clubs"],["176","Videos","71% coverage"],["6","Needs review","3 possible duplicates"]].map((s,i)=><article key={s[1]}><i>{["⚔","◎","▶","!"][i]}</i><span><small>{s[1]}</small><b>{s[0]}</b><em>{s[2]}</em></span></article>)}</section><div className="two"><section className="panel"><div className="panelHead"><div><span className="eyebrow">RECENT RECORDS</span><h3>Latest verified fights</h3></div><button onClick={()=>setView("fights")}>View all →</button></div>{bouts.slice(0,4).map(b=><div className="bout" key={b.id}><Badge>{b.cat}</Badge><span><b>{b.match}</b><small>{b.event} · {b.division}</small></span><strong>{b.result}</strong><Badge tone={b.verify==="Verified"?"green":"gold"}>{b.verify}</Badge></div>)}</section><section className="panel"><div className="panelHead"><div><span className="eyebrow">DATA QUALITY</span><h3>Integrity checks</h3></div></div><div className="quality"><div className="ring"><b>94</b><small>quality score</small></div>{[["Athlete identity",97],["Competition links",95],["Division detail",91],["Video coverage",71]].map(q=><label key={q[0]}><span>{q[0]} <b>{q[1]}%</b></span><i><em style={{width:q[1]+"%"}}/></i></label>)}</div><button className="warning" onClick={()=>setView("duplicates")}>Review 3 possible duplicates →</button></section></div><section className="panel timeline"><div className="panelHead"><div><span className="eyebrow">AUDIT TRAIL</span><h3>Recent system activity</h3></div><button onClick={()=>setView("audit")}>Full history →</button></div>{audits.slice(0,4).map((a,i)=><div className="audit" key={i}><i className="auditDot"/><small>{a[0]}</small><span><b>{a[2]}</b><em>{a[1]} · {a[3]}</em></span></div>)}</section></>}
 {view==="processing"&&<><ProcessingView notice={notice}/><VerificationExtras notice={notice}/></>} 
 {view==="profiles"&&<AthleteProfiles notice={notice}/>} 
 {view==="matchups"&&<MatchupIntelligence notice={notice}/>} 
 {view==="coaching"&&<CoachingAnalysis notice={notice}/>} 
 {view==="sync"&&<PlatformSync notice={notice}/>} 
 {view==="consent"&&<ConsentCentre notice={notice}/>} 
 {view==="analysis"&&<RuleAwareAnalysis notice={notice}/>} 
 {view==="youtube"&&<YouTubeSources notice={notice} openAnalysis={()=>setView("analysis")}/>} 
 {view==="training"&&<TrainingHealth notice={notice}/>} 
 {view==="rankings"&&<RankingsScouting notice={notice}/>} 
 {view==="federationPlatform"&&<FederationPlatform notice={notice}/>} 
 {view==="operations"&&<OperationsCentre notice={notice}/>} 
 {view==="competitionDay"&&<CompetitionDay notice={notice}/>} 
 {view==="mobile"&&<MobileExperience notice={notice}/>} 
 {view==="coachCommand"&&<CoachCommandMobile notice={notice}/>} 
 {view==="clubMission"&&<ClubMissionBoard notice={notice}/>} 
 {view==="eventReplay"&&<MobileEventReplay notice={notice}/>} 
 {view==="athletes"&&<ListHeader title="Athlete registry" text="Identity-controlled profiles linked to clubs, categories and fight history." query={query} setQuery={setQuery}/>} 
 {view==="athletes"&&<section className="cards">{athletes.filter(a=>Object.values(a).join(" ").toLowerCase().includes(query.toLowerCase())).map(a=><article className="athlete" key={a.id}><div className="initial">{a.name.split(" ").map(x=>x[0]).join("")}</div><div><Badge tone={a.status==="Verified"?"green":"gold"}>{a.status}</Badge><h3>{a.name}</h3><p>{a.club}</p><div><span><b>{a.record}</b>record</span><span><b>{a.grade}</b>grade</span></div><small>{a.id} · {a.nation}</small></div><button>•••</button></article>)}</section>}
 {view==="competitions"&&<CompetitionDiscovery notice={notice}/>} 
 {view==="entryPlanner"&&<EntryReadiness notice={notice}/>}
 {view==="eventPack"&&<CompetitionOperations notice={notice}/>}
 {view==="liveSchedule"&&<LiveRingBoard notice={notice}/>}
 {view==="coachClashes"&&<CoachClashBoard notice={notice}/>}
 {view==="resultsCentre"&&<ResultsMedalCentre notice={notice}/>}
 {view==="postReview"&&<PostEventReview notice={notice} openDevelopment={()=>openView("developmentPlans")}/>}
 {view==="developmentPlans"&&<DevelopmentPlans notice={notice}/>}
 {view==="progressTracking"&&<ProgressTracking notice={notice}/>}
 {view==="seasonPlanner"&&<SeasonPlanner notice={notice}/>}
 {view==="actionCentre"&&<ActionCentre notice={notice}/>}
 {view==="loadMonitor"&&<LoadMonitor notice={notice}/>}
 {view==="squadSelection"&&<SquadSelection notice={notice}/>}
 {view==="logisticsBudget"&&<LogisticsBudget notice={notice}/>}
 {view==="eventLaunch"&&<EventLaunch notice={notice}/>}
 {view==="teamItinerary"&&<TeamItinerary notice={notice}/>}
 {view==="teamBriefing"&&<TeamBriefing notice={notice}/>}
 {view==="eventCloseout"&&<EventCloseout notice={notice} openReview={()=>openView("postReview")}/>}
 {view==="fights"&&<><ListHeader title="Fight registry" text="Verified results with provenance, division links and attached footage." query={query} setQuery={setQuery}/><div className="filters">{["All","PF","LC","KL","K1"].map(c=><button className={cat===c?"active":""} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="table"><table><thead><tr><th>Record</th><th>Competition</th><th>Category</th><th>Match-up</th><th>Result</th><th>Source</th><th>Status</th><th>Video</th></tr></thead><tbody>{filtered.map(b=><tr key={b.id}><td><b>{b.id}</b></td><td>{b.event}</td><td><Badge>{b.cat}</Badge><small>{b.division}</small></td><td><b>{b.match}</b></td><td><strong>{b.result}</strong></td><td>{b.source}</td><td><Badge tone={b.verify==="Verified"?"green":"gold"}>{b.verify}</Badge></td><td>{b.video?<button className="play">▶</button>:"—"}</td></tr>)}</tbody></table></div></>}
 {view==="rules"&&<RulesView federation={federation} setFederation={setFederation} discipline={discipline} setDiscipline={setDiscipline}/>}
 {view==="duplicates"&&<><ListHeader title="Duplicate review" text="Potential duplicate entities ranked by confidence; every resolution is audited." query={query} setQuery={setQuery}/><section className="dupes">{dupes.map(d=><article className="panel" key={d.id}><div className="dupeTop"><Badge tone="gold">{d.type}</Badge><strong>{d.score}% match</strong></div><div className="compare"><span><small>PRIMARY RECORD</small><b>{d.a}</b></span><i>≈</i><span><small>CANDIDATE</small><b>{d.b}</b></span></div><p>{d.reasons}</p><div className="dupeActions"><button onClick={()=>{setDupes(x=>x.filter(y=>y.id!==d.id));notice("Marked as separate records; audit entry created")}}>Not a duplicate</button><button className="primary" onClick={()=>{setDupes(x=>x.filter(y=>y.id!==d.id));notice("Records queued for safe merge")}}>Merge records</button></div></article>)}</section></>}
 {view==="permissions"&&<><ListHeader title="Role-based access" text="Least-privilege access for athletes, parents, coaches, clubs and system administrators." query={query} setQuery={setQuery}/><section className="roles">{[["System administrator","Full database, audit and role control","1"],["Club administrator","Own club athletes, fights and private media","4"],["Coach","Assigned athletes, fight review and notes","12"],["Parent","Linked junior athlete and approved media","38"],["Athlete","Own profile, fights and shared media","92"]].map((r,i)=><article className="panel" key={r[0]}><i>{["◆","♜","♙","♡","◎"][i]}</i><span><h3>{r[0]}</h3><p>{r[1]}</p></span><b>{r[2]} users</b><button>Manage</button></article>)}</section></>}
 {view==="audit"&&<><ListHeader title="Immutable audit history" text="Who changed what, when, and the before/after state of every write." query={query} setQuery={setQuery}/><section className="panel auditPage">{audits.map((a,i)=><div className="audit" key={i}><i className="auditDot"/><small>{a[0]}</small><span><b>{a[2]}</b><em>{a[1]}</em></span><code>{a[3]}</code><button>View change</button></div>)}</section></>}
 </section><nav className="mobileDock" aria-label="Primary navigation">{mobilePrimary.map(item=><button key={item[0]} className={`${view===item[0]?"active":""} ${item[0]==="liveSchedule"?"live":""}`} onClick={()=>openView(item[0])}><i>{item[2]}</i><span>{item[1]}</span></button>)}<button className={!mobilePrimary.some(item=>item[0]===view)||mobileMore?"active":""} onClick={()=>setMobileMore(true)} aria-expanded={mobileMore}><i>☰</i><span>More</span></button></nav>{mobileMore&&<div className="mobileMoreBackdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setMobileMore(false)}}><section className="mobileMoreSheet" role="dialog" aria-modal="true" aria-label="All FightEye sections"><i className="mobileSheetHandle"/><div className="mobileMoreHead"><div><h2>FightEye</h2><p>All tools · Phase 63</p></div><button onClick={()=>setMobileMore(false)} aria-label="Close menu">×</button></div><div className="mobileMoreGrid">{nav.map(item=><button key={item[0]} className={view===item[0]?"active":""} onClick={()=>openView(item[0])}><i>{item[2]}</i><span>{item[1]}</span></button>)}</div></section></div>}{toast&&<div className="toast">{toast}</div>}{modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={()=>setModal(null)}>×</button><Badge tone="gold">PHASE 1 RECORD</Badge><h2>{modal==="video"?"Store private fight video":`Add ${modal}`}</h2>{modal==="video"?<><div className="upload" onClick={()=>file.current?.click()}><input hidden ref={file} type="file" accept="video/*" onChange={e=>upload(e.target.files?.[0])}/><i>⇧</i><b>{busy?"Uploading securely…":"Choose fight footage"}</b><small>Private by default · metadata recorded in the database</small></div></>:<Fields type={modal}/>} {modal!=="video"&&<button disabled={busy} className="primary submit">{busy?"Saving…":"Save record & audit change"}</button>}</form></div>}</main>}
function RulesView({federation,setFederation,discipline,setDiscipline}:{federation:Federation,setFederation:(x:Federation)=>void,discipline:Discipline,setDiscipline:(x:Discipline)=>void}){const feds:Federation[]=["WAKO","ISKA","ICO","WKKC","WKU"],disciplines:Discipline[]=["PF","LC","KL","K1","K2"];return <><section className="listHead"><div><span className="eyebrow">VERSIONED FEDERATION RULES</span><h2>Scoring criteria</h2><p>Compare scoring without blending different federation rules.</p></div><Badge tone="green">SOURCE TRACKED</Badge></section><section className="rulePicker"><div><small>FEDERATION</small>{feds.map(x=><button key={x} className={federation===x?"active":""} onClick={()=>setFederation(x)}>{x}</button>)}</div><div><small>DISCIPLINE</small>{disciplines.map(x=><button key={x} className={discipline===x?"active":""} onClick={()=>setDiscipline(x)}>{x}</button>)}</div></section><section className="rulesLayout"><article className="panel ruleCard"><div className="ruleTitle"><div><Badge tone={discipline==="K2"?"gold":"green"}>{discipline==="K2"?"UNVERIFIED CATEGORY":"RULESET AVAILABLE"}</Badge><h3>{federation} · {discipline}</h3><p>{federationSources[federation].version}</p></div><strong>{discipline}</strong></div><div className="criteria">{scoring[discipline].map((x,i)=><div key={x}><i>{i+1}</i><span>{x}</span></div>)}</div>{exceptions[federation]?.[discipline]?.map(x=><div className="ruleNotice" key={x}>! {x}</div>)}</article><aside className="panel sourceCard"><span className="eyebrow">SOURCE & CONTROL</span><h3>Rules provenance</h3><dl><div><dt>Federation</dt><dd>{federation}</dd></div><div><dt>Version</dt><dd>{federationSources[federation].version}</dd></div><div><dt>Status</dt><dd>{discipline==="K2"?"Unsupported until documented":"Reference criteria"}</dd></div></dl><p>{federationSources[federation].note}</p><a href={federationSources[federation].url} target="_blank" rel="noreferrer">Open governing source ↗</a><div className="caution"><b>Competition rules take precedence</b><span>Confirm the event-issued rules pack, age band and jurisdiction before officiating.</span></div></aside></section><section className="panel matrix"><div className="panelHead"><div><span className="eyebrow">COVERAGE MATRIX</span><h3>Federation × discipline status</h3></div></div><div className="table"><table><thead><tr><th>Federation</th>{disciplines.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{feds.map(f=><tr key={f}><td><b>{f}</b></td>{disciplines.map(d=><td key={d}><Badge tone={d==="K2"?"gold":d==="K1"&&["ISKA","ICO","WKKC"].includes(f)?"gold":"green"}>{d==="K2"?"No official K2":d==="K1"&&["ISKA","ICO","WKKC"].includes(f)?"Event check":"Mapped"}</Badge></td>)}</tr>)}</tbody></table></div></section></>}
function ListHeader({title,text,query,setQuery}:{title:string,text:string,query:string,setQuery:(x:string)=>void}){return <section className="listHead"><div><span className="eyebrow">CANONICAL RECORDS</span><h2>{title}</h2><p>{text}</p></div><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search records…"/></label></section>}
function Fields({type}:{type:string}){if(type==="athlete")return <div className="fields"><label>First name<input name="firstName" required/></label><label>Last name<input name="lastName" required/></label><label>Display name<input name="displayName"/></label><label>Date of birth<input name="dateOfBirth" type="date"/></label><label>Nationality<input name="nationality" placeholder="GB"/></label><label>Grade<input name="grade" placeholder="Black belt"/></label></div>;if(type==="club")return <div className="fields"><label>Club name<input name="name" required/></label><label>City<input name="city"/></label><label>Country<input name="country" defaultValue="GB"/></label><label>Contact email<input name="contactEmail" type="email"/></label></div>;if(type==="competition")return <div className="fields"><label>Competition name<input name="name" required/></label><label>Start date<input name="startDate" type="date" required/></label><label>End date<input name="endDate" type="date"/></label><label>Venue<input name="venue"/></label><label>City<input name="city"/></label><label>Country<input name="country"/></label><label className="wide">Official source URL<input name="sourceUrl" type="url"/></label></div>;return <div className="fields"><label className="wide">User email<input name="userEmail" type="email" required/></label><label className="wide">Role<select name="role"><option value="athlete">Athlete</option><option value="parent">Parent</option><option value="coach">Coach</option><option value="club_admin">Club administrator</option><option value="system_admin">System administrator</option></select></label></div>}
