(function(){
'use strict';
const VERSION='v195–v196';
const events=(window.FIGHTEYE_EVENTS||[]).map(e=>({...e,status:statusFor(e)})).sort((a,b)=>new Date(a.start)-new Date(b.start));
const athletes=window.FIGHTEYE_ATHLETES||[];
const persisted=readStore();
const state={tab:'events',apiHealth:'Not checked',syncReport:null,integrationSource:'All',analyticsAthlete:persisted.analyticsAthlete||athletes[0]?.id||'',analyticsGoal:persisted.analyticsGoal||'Ranking',productionReport:null,query:'',filter:'All',saved:new Set(persisted.saved||['gb-grand-slam-2-2026','wku-worlds-2026']),budget:persisted.budget||{travel:180,hotel:240,entry:90,food:80},attendance:persisted.attendance||{},parentAthlete:persisted.parentAthlete||athletes[0]?.id||'',rankFinish:1,adminEvents:persisted.adminEvents||[],toast:''};
state.adminEvents.forEach(e=>{if(!events.some(x=>x.id===e.id))events.push({...e,status:statusFor(e)});});
events.sort((a,b)=>new Date(a.start)-new Date(b.start));
const app=document.getElementById('app');
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readStore(){try{return JSON.parse(localStorage.getItem('fighteye-v192')||'{}')}catch{return{}}}
function saveStore(){localStorage.setItem('fighteye-v192',JSON.stringify({saved:[...state.saved],budget:state.budget,attendance:state.attendance,parentAthlete:state.parentAthlete,adminEvents:state.adminEvents,analyticsAthlete:state.analyticsAthlete,analyticsGoal:state.analyticsGoal}));}
function statusFor(e){const n=new Date(),s=new Date(e.start+'T00:00:00'),en=new Date(e.end+'T23:59:59'),cl=new Date(e.closing+'T23:59:59');if(n>=s&&n<=en)return'Competition Live';if(n>en)return'Results Available';if(n>cl)return'Registration Closed';return Math.ceil((cl-n)/86400000)<=14?'Closing Soon':'Registration Open';}
function fmt(d){return new Date(d+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});}
function days(d){return Math.ceil((new Date(d+'T23:59:59')-new Date())/86400000);}
function nav(){const items=[['events','🏆','Events'],['passport','🪪','Passport'],['travel','✈️','Travel'],['club','🥋','ClubOS'],['more','☰','More']];const more=['backend','integrations','analytics','production','sync','replay','rankings','parent','admin'].includes(state.tab);return `<nav class="nav">${items.map(x=>`<button class="${state.tab===x[0]||(x[0]==='more'&&more)?'active':''}" data-tab="${x[0]}">${x[1]}<span>${x[2]}</span></button>`).join('')}</nav>`;}
function header(){return `<header class="topbar"><div class="brand"><img src="assets/fighteye-logo.jpg" alt="FightEye"><div><h1>FightEye ${VERSION}</h1><small>AI analytics • Integrations • Production diagnostics • Competition operations</small></div></div><button class="icon-btn" id="themeBtn" aria-label="Toggle colour theme">◐</button></header>`;}
function eventCard(e){const saved=state.saved.has(e.id);return `<article class="event-card"><div class="event-art" style="--image:${esc(e.image)}"><span class="logo-pill">${esc(e.org)}</span><span class="status">${esc(e.status)}</span></div><div class="event-body"><h3>${saved?'⭐ ':''}${esc(e.name)}</h3><p>${esc(e.flag)} ${esc(e.city)} • ${esc(e.venue)}</p><div class="meta"><div><b>${fmt(e.start)}</b><small>Starts</small></div><div><b>${days(e.closing)>0?days(e.closing)+' days':'Closed'}</b><small>Registration</small></div><div><b>${esc(e.athletes)}</b><small>Watched</small></div></div><div class="actions"><button class="ghost" data-save="${esc(e.id)}">${saved?'Saved':'Save'}</button><button class="primary" data-open="${esc(e.id)}">Open</button></div></div></article>`;}
function eventsView(){const q=state.query.toLowerCase();const list=events.filter(e=>(state.filter==='All'||e.status===state.filter||e.collection.includes(state.filter))&&[e.name,e.org,e.city,e.country].join(' ').toLowerCase().includes(q));return `<section class="hero"><span class="logo-pill">Four new phases complete</span><h2>Plan, compete, review and improve.</h2><p>The competition platform now connects event planning with replay reports, ranking scenarios, family updates and editable local data.</p></section><section class="toolbar"><input id="search" class="search" value="${esc(state.query)}" placeholder="Search competitions"><select id="filter" class="search"><option>All</option>${['Registration Open','Closing Soon','Competition Live','Results Available','UK','Europe','World Cups'].map(x=>`<option ${state.filter===x?'selected':''}>${x}</option>`).join('')}</select></section><section class="stats"><button class="stat" data-filter-stat="All"><strong>${events.length}</strong><span>Events</span></button><button class="stat" data-filter-stat="Closing Soon"><strong>${events.filter(e=>e.status==='Closing Soon').length}</strong><span>Closing soon</span></button><button class="stat"><strong>${state.saved.size}</strong><span>Saved</span></button><button class="stat"><strong>${athletes.length}</strong><span>Athletes</span></button></section><section class="section"><div class="section-head"><div><h2>Upcoming competitions</h2><small>${list.length} matching events</small></div></div><div class="carousel">${list.length?list.map(eventCard).join(''):'<div class="panel"><h3>No matching events</h3><button class="button" id="reset">Reset filters</button></div>'}</div></section>`;}
function passportView(){return `<section class="section"><div class="section-head"><div><h2>Athlete Passport</h2><small>Digital documents and competition readiness</small></div></div><div class="grid">${athletes.map(a=>`<article class="panel athlete"><div class="avatar">${esc(a.flag)}</div><h3>${esc(a.name)}</h3><p>${esc(a.club)} • ${esc(a.ranking)}</p><div class="check-grid"><span>Licence <b>${esc(a.licence)}</b></span><span>Insurance <b>${esc(a.insurance)}</b></span><span>Weight <b>${esc(a.weight)}</b></span><span>Passport <b>${esc(a.passport)}</b></span><span>Medical <b>${esc(a.medical)}</b></span><span>Record <b>${esc(a.record)}</b></span></div><button class="button" data-pass="${esc(a.id)}">Open QR pass</button></article>`).join('')}</div></section>`;}
function travelView(){const total=Object.values(state.budget).reduce((a,b)=>a+Number(b),0);const e=events.find(x=>state.saved.has(x.id))||events[0];return `<section class="section"><div class="section-head"><div><h2>Travel & Budget Centre</h2><small>Itineraries, costs and packing</small></div></div><div class="grid"><div class="panel"><h3>${esc(e.flag)} ${esc(e.name)}</h3><p>${esc(e.travel)} • ${esc(e.hotel)}</p><p>${fmt(e.start)}–${fmt(e.end)}</p><button class="button" data-open="${esc(e.id)}">Open itinerary</button></div><div class="panel"><h3>Budget planner</h3>${Object.entries(state.budget).map(([k,v])=>`<label>${k[0].toUpperCase()+k.slice(1)} <input class="budget" data-budget="${k}" type="number" min="0" value="${v}"></label>`).join('')}<div class="budget-total">Estimated total <strong>£${total}</strong></div></div><div class="panel"><h3>Packing checklist</h3>${['Passport/licence','Uniform','Gloves and footpads','Water and food','Chargers','Medication'].map((x,i)=>`<label class="task"><input type="checkbox" ${i<2?'checked':''}> ${x}</label>`).join('')}</div></div></section>`;}
function clubView(){return `<section class="section"><div class="section-head"><div><h2>Prestige Martial Arts ClubOS</h2><small>Team attendance and compliance</small></div></div><div class="stats"><div class="stat"><strong>${athletes.length}</strong><span>Active athletes</span></div><div class="stat"><strong>11</strong><span>Events entered</span></div><div class="stat"><strong>42</strong><span>Medals</span></div><div class="stat"><strong>92%</strong><span>Compliance</span></div></div><div class="grid">${athletes.map(a=>`<div class="panel"><h3>${esc(a.name)}</h3><p>${esc(a.next)}</p><label class="task"><input type="checkbox" data-att="${esc(a.id)}" ${state.attendance[a.id]?'checked':''}> Attending tonight</label><p>Licence: ${esc(a.licence)}</p><p>Medical: ${esc(a.medical)}</p></div>`).join('')}<div class="panel"><h3>Coach actions</h3><button class="button" id="teamExport">Export team list</button><button class="ghost" id="checkCompliance">Check compliance</button></div></div></section>`;}
function moreView(){const modules=[['backend','🗄️','Backend Foundation','API health, persistence, security and deployment diagnostics'],['integrations','🔄','Integrations Engine','Source adapters, validation, deduplication and sync reports'],['analytics','🧠','AI & Analytics','Recommendations, projections and season intelligence'],['production','🚀','Production & DevOps','Monitoring, release checks and deployment readiness'],['sync','🔔','Smart Sync','Notifications, offline health and diagnostics'],['replay','🎬','Event Replay','Create post-event reports and media summaries'],['rankings','📈','Rankings Lab','Compare athletes and simulate ranking movement'],['parent','👨‍👩‍👧','Parent Companion','Family schedules, travel and live updates'],['admin','🛠️','Admin CMS','Add events, export data and validate records']];return `<section class="section"><div class="section-head"><div><h2>More tools</h2><small>Open a specialist FightEye module</small></div></div><div class="grid module-grid">${modules.map(m=>`<button class="panel module" data-tab="${m[0]}"><span>${m[1]}</span><h3>${m[2]}</h3><p>${m[3]}</p></button>`).join('')}</div></section>`;}
function syncView(){return `<section class="section"><div class="section-head"><div><h2>Smart Sync & Diagnostics</h2><small>Resilient background updates and data checks</small></div></div><div class="grid"><div class="panel"><h3>Notification rules</h3>${['Registration deadlines','Schedule changes','Opponent changes','Results available','Travel reminders'].map((x,i)=>`<label class="task"><input type="checkbox" ${i<4?'checked':''}> ${x}</label>`).join('')}</div><div class="panel"><h3>Sync health</h3><p>Event calendar: <b>Ready</b></p><p>Athlete passport: <b>Ready</b></p><p>Offline cache: <b>Ready</b></p><button class="button" id="syncNow">Sync now</button></div><div class="panel"><h3>Diagnostics</h3><p>Events: ${events.length}</p><p>Athletes: ${athletes.length}</p><p>Duplicate event IDs: ${duplicateIds(events)}</p><p>Invalid event records: ${invalidEvents().length}</p><button class="ghost" id="runTests">Run feature tests</button></div></div></section>`;}
function replayView(){const past=events.filter(e=>e.status==='Results Available');const display=past.length?past:events.slice(0,3);return `<section class="section"><div class="section-head"><div><h2>Event Replay & Media</h2><small>Phase 189 • turn competition data into a shareable report</small></div></div><div class="grid">${display.map((e,i)=>`<article class="panel replay-card"><div class="replay-thumb" style="--image:${esc(e.image)}"><span>▶</span></div><h3>${esc(e.name)}</h3><p>${fmt(e.start)} • ${esc(e.city)}</p><div class="medal-row"><span>🥇 ${i+1}</span><span>🥈 ${i}</span><span>🥉 ${i+2}</span></div><div class="actions"><button class="ghost" data-replay="${esc(e.id)}">Preview</button><button class="button" data-report="${esc(e.id)}">Download report</button></div></article>`).join('')}</div></section>`;}
function rankingsView(){const a=athletes[0];const projected=Math.max(1,7-(4-state.rankFinish));return `<section class="section"><div class="section-head"><div><h2>Rankings Lab</h2><small>Phase 190 • compare form and simulate outcomes</small></div></div><div class="grid"><div class="panel"><h3>${esc(a.name)} ranking simulator</h3><p>Current: <b>${esc(a.ranking)}</b></p><label>Projected finish: <b>${placement(state.rankFinish)}</b><input id="rankSlider" class="range" type="range" min="1" max="8" value="${state.rankFinish}"></label><div class="rank-result"><small>Estimated next ranking</small><strong>#${projected}</strong><span>${projected<7?'▲ likely improvement':'— limited movement'}</span></div></div><div class="panel"><h3>Athlete comparison</h3>${athletes.map((x,i)=>`<div class="compare-row"><span>${esc(x.flag)} ${esc(x.name)}</span><b>${esc(x.record)}</b><meter min="0" max="100" value="${82-i*8}"></meter></div>`).join('')}</div><div class="panel"><h3>Season intelligence</h3><p>Best opportunity: <b>GB Grand Slam 2</b></p><p>Highest difficulty: <b>WAKO Junior Worlds</b></p><p>Recommended load: <b>3 events in 8 weeks</b></p><button class="button" id="seasonExport">Export season plan</button></div></div></section>`;}
function parentView(){const a=athletes.find(x=>x.id===state.parentAthlete)||athletes[0];const next=events.find(e=>e.name===a.next)||events.find(e=>state.saved.has(e.id))||events[0];return `<section class="section"><div class="section-head"><div><h2>Parent Companion</h2><small>Phase 191 • simpler information for families</small></div><select id="parentAthlete" class="search source-select">${athletes.map(x=>`<option value="${esc(x.id)}" ${x.id===a.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="family-hero panel"><div class="avatar">${esc(a.flag)}</div><div><h3>${esc(a.name)}</h3><p>${esc(a.club)} • ${esc(a.weight)}</p></div><span class="status">Ready</span></div><div class="grid"><div class="panel"><h3>Next competition</h3><p><b>${esc(next.name)}</b></p><p>${fmt(next.start)} • ${esc(next.venue)}</p><p>${esc(next.travel)}</p><button class="button" data-open="${esc(next.id)}">Open event</button></div><div class="panel"><h3>Family updates</h3>${['Notify 60 minutes before fight','Notify when bracket changes','Notify when result is posted','Share estimated finish time'].map((x,i)=>`<label class="task"><input type="checkbox" ${i<3?'checked':''}> ${x}</label>`).join('')}</div><div class="panel"><h3>Weekend essentials</h3><p>Parking: <b>Venue car park</b></p><p>Weather: <b>${esc(next.weather)}</b></p><p>Emergency contact: <b>Coach team</b></p><button class="ghost" id="familyShare">Share family briefing</button></div></div></section>`;}
function adminView(){return `<section class="section"><div class="section-head"><div><h2>Admin CMS & Data Health</h2><small>Phase 192 • edit without touching code</small></div></div><div class="grid"><form class="panel" id="eventForm"><h3>Add local competition</h3><label>Name<input class="budget" name="name" required maxlength="80"></label><label>Organisation<input class="budget" name="org" required maxlength="40"></label><label>City<input class="budget" name="city" required maxlength="50"></label><label>Start date<input class="budget" name="start" type="date" required></label><label>Closing date<input class="budget" name="closing" type="date" required></label><button class="button" type="submit">Add event</button></form><div class="panel"><h3>Data health</h3><p>Events: <b>${events.length}</b></p><p>Custom events: <b>${state.adminEvents.length}</b></p><p>Duplicate IDs: <b>${duplicateIds(events)}</b></p><p>Invalid records: <b>${invalidEvents().length}</b></p><p>Placeholder registration links: <b>${events.filter(e=>e.registration==='#').length}</b></p><button class="ghost" id="validateLinks">Validate records</button></div><div class="panel"><h3>Data tools</h3><button class="button" id="exportData">Export JSON backup</button><button class="ghost" id="clearCustom">Remove custom events</button><p><small>Custom event changes are stored locally on this device.</small></p></div></div></section>`;}

function backendView(){return `<section class="section"><div class="section-head"><div><h2>Backend Foundation</h2><small>Phase 193 • API, persistence, security and deployment readiness</small></div></div><div class="stats"><div class="stat"><strong>${events.length}</strong><span>Event records</span></div><div class="stat"><strong>${athletes.length}</strong><span>Athlete records</span></div><div class="stat"><strong>${state.apiHealth==='Healthy'?'✓':'—'}</strong><span>API health</span></div><div class="stat"><strong>v1</strong><span>API version</span></div></div><div class="grid"><div class="panel"><h3>API health</h3><p>Status: <b>${esc(state.apiHealth)}</b></p><p>Endpoint: <code>/.netlify/functions/health</code></p><button class="button" id="healthCheck">Run health check</button></div><div class="panel"><h3>Data services</h3><p>Events API: <b>Configured</b></p><p>Validation: <b>Enabled</b></p><p>Local fallback: <b>Enabled</b></p><p>Audit metadata: <b>Enabled</b></p></div><div class="panel"><h3>Security baseline</h3><p>Security headers: <b>Enabled</b></p><p>Input escaping: <b>Enabled</b></p><p>Rate-limit hook: <b>Ready</b></p><p>Environment template: <b>Included</b></p></div><div class="panel"><h3>Persistence test</h3><p>Saved events and admin records use versioned local storage while the remote database connector is optional.</p><button class="ghost" id="persistenceTest">Test persistence</button></div></div></section>`;}
function integrationsView(){const sources=['All','Sportdata','Smoothcomp','Kihapp','WAKO','WKU','ICO','ISKA'];const report=state.syncReport;return `<section class="section"><div class="section-head"><div><h2>Integrations Engine</h2><small>Phase 194 • source adapters, validation and controlled synchronisation</small></div><select id="integrationSource" class="search source-select">${sources.map(x=>`<option ${state.integrationSource===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="grid integration-grid">${sources.slice(1).map((x,i)=>`<article class="panel source-card"><div class="source-head"><span>${['🏟️','🥋','📋','🌍','🏆','🇬🇧','⭐'][i]}</span><div><h3>${x}</h3><small>${i<3?'Competition platform':'Organisation feed'}</small></div></div><p>Adapter: <b>Ready</b></p><p>Validation: <b>Active</b></p><p>Last sync: <b>${report?'Just now':'Not run'}</b></p></article>`).join('')}</div><div class="panel sync-console"><h3>Synchronisation console</h3><p>Fetches demo source records, validates required fields, detects duplicates and preserves manual edits.</p><div class="actions wide"><button class="button" id="runIntegrationSync">Run controlled sync</button><button class="ghost" id="exportSync">Export sync report</button></div>${report?`<div class="sync-report"><p><b>${report.checked}</b> records checked</p><p><b>${report.accepted}</b> accepted</p><p><b>${report.duplicates}</b> duplicates blocked</p><p><b>${report.invalid}</b> invalid quarantined</p></div>`:''}</div></section>`;}

function analyticsView(){
 const a=athletes.find(x=>x.id===state.analyticsAthlete)||athletes[0];
 const scored=events.filter(e=>e.status!=='Results Available').map(e=>{const distance=parseInt(String(e.distance).replace(/[^0-9]/g,''))||500;const score=Math.max(20,100-(e.difficulty||3)*7-Math.min(28,distance/45)+(state.saved.has(e.id)?14:0)+(e.org.includes('WAKO')?8:0));return{...e,score:Math.round(score)}}).sort((x,y)=>y.score-x.score);
 const best=scored[0]||events[0];
 const formWins=(a.form.match(/W/g)||[]).length;
 const confidence=Math.min(94,58+formWins*6);
 return `<section class="section"><div class="section-head"><div><h2>AI & Analytics Platform</h2><small>Phase 195 • explainable recommendations, projections and season planning</small></div><select id="analyticsAthlete" class="search source-select">${athletes.map(x=>`<option value="${esc(x.id)}" ${x.id===a.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="stats"><div class="stat"><strong>${confidence}%</strong><span>Form confidence</span></div><div class="stat"><strong>${scored.length}</strong><span>Events analysed</span></div><div class="stat"><strong>${formWins}/5</strong><span>Recent wins</span></div><div class="stat"><strong>${best?best.score:0}</strong><span>Best fit score</span></div></div><div class="grid"><article class="panel insight-card"><h3>Recommended next event</h3><div class="recommendation-score">${best?best.score:0}</div><p><b>${esc(best?.name||'No event available')}</b></p><p>${esc(best?.flag||'')} ${esc(best?.city||'')} • ${esc(best?.org||'')}</p><p class="muted">High score reflects travel, difficulty, saved status and organisation fit. This is guidance, not a guaranteed outcome.</p><button class="button" data-open="${esc(best?.id||'')}">Review event</button></article><article class="panel"><h3>Season projection</h3><div class="analytics-bars">${[['Activity',82],['Ranking potential',76],['Travel efficiency',69],['Medal opportunity',73]].map(([n,v])=>`<label>${n}<span><i style="width:${v}%"></i></span><b>${v}</b></label>`).join('')}</div><button class="ghost" id="analyticsExport">Export analytics report</button></article><article class="panel"><h3>Competition shortlist</h3>${scored.slice(0,4).map((e,i)=>`<button class="shortlist" data-open="${esc(e.id)}"><span>${i+1}</span><div><b>${esc(e.name)}</b><small>${esc(e.org)} • ${e.score}/100 fit</small></div></button>`).join('')}</article><article class="panel"><h3>Goal planner</h3><select id="analyticsGoal" class="search">${['Ranking','Medals','Experience','Travel efficiency'].map(x=>`<option ${state.analyticsGoal===x?'selected':''}>${x}</option>`).join('')}</select><p>Current goal: <b>${esc(state.analyticsGoal)}</b></p><p>Suggested load: <b>${state.analyticsGoal==='Experience'?'4 events in 10 weeks':'3 events in 12 weeks'}</b></p><p>Recovery buffer: <b>14 days after major international events</b></p></article></div></section>`;
}
function productionView(){const r=state.productionReport;return `<section class="section"><div class="section-head"><div><h2>Production & DevOps</h2><small>Phase 196 • release safety, monitoring and deployment readiness</small></div></div><div class="stats"><div class="stat"><strong>${r?r.passed:'—'}</strong><span>Checks passed</span></div><div class="stat"><strong>${r?r.failed:'—'}</strong><span>Checks failed</span></div><div class="stat"><strong>v196</strong><span>Release channel</span></div><div class="stat"><strong>${navigator.onLine?'Online':'Offline'}</strong><span>Network</span></div></div><div class="grid"><article class="panel"><h3>Release gate</h3><p>Runs browser capability, data integrity, storage and service-worker checks.</p><button class="button" id="runProductionChecks">Run release checks</button>${r?`<div class="release-list">${r.tests.map(t=>`<p class="${t.ok?'pass':'fail'}"><b>${t.ok?'✓':'✕'}</b> ${esc(t.name)}</p>`).join('')}</div>`:''}</article><article class="panel"><h3>Observability</h3><p>API health: <b>${esc(state.apiHealth)}</b></p><p>Events loaded: <b>${events.length}</b></p><p>Duplicate IDs: <b>${duplicateIds(events)}</b></p><p>Invalid records: <b>${invalidEvents().length}</b></p><button class="ghost" id="productionHealth">Check API + metrics</button></article><article class="panel"><h3>Deployment pipeline</h3><ol class="pipeline"><li>Syntax and data validation</li><li>Function smoke tests</li><li>Asset/reference checks</li><li>Production ZIP integrity</li><li>Netlify preview deployment</li></ol><p><small>GitHub Actions workflow and local test commands are included.</small></p></article><article class="panel"><h3>Recovery controls</h3><button class="ghost" id="clearCaches">Clear app caches</button><button class="ghost" id="exportDiagnostics">Export diagnostics</button><p><small>Cache clearing does not remove saved events or custom CMS records.</small></p></article></div></section>`;}

function placement(n){return n===1?'Gold':n===2?'Silver':n===3?'Bronze':`${n}th`;}
function duplicateIds(xs){return xs.length-new Set(xs.map(x=>x.id)).size;}
function invalidEvents(){return events.filter(e=>!e.id||!e.name||!e.start||!e.end||!e.closing);}
function sheet(){return `<aside class="sheet" id="sheet" aria-label="Details panel"></aside>`;}
function toast(){return state.toast?`<div class="toast" role="status">${esc(state.toast)}</div>`:'';}
function render(){const views={events:eventsView,passport:passportView,travel:travelView,club:clubView,more:moreView,backend:backendView,integrations:integrationsView,analytics:analyticsView,production:productionView,sync:syncView,replay:replayView,rankings:rankingsView,parent:parentView,admin:adminView};app.innerHTML=header()+(views[state.tab]||moreView)()+nav()+sheet()+toast();bind();}
function notify(text){state.toast=text;render();setTimeout(()=>{if(state.toast===text){state.toast='';render();}},1800);}
function openEvent(id){const e=events.find(x=>x.id===id);if(!e)return;const s=$('#sheet');s.innerHTML=`<button class="close" id="close">Close</button><h2>${esc(e.flag)} ${esc(e.name)}</h2><p>${esc(e.org)} • ${esc(e.city)} • ${esc(e.venue)}</p><div class="grid"><div class="panel"><h3>Registration</h3><p>${esc(e.status)} • closes ${fmt(e.closing)}</p></div><div class="panel"><h3>Travel</h3><p>${esc(e.travel)}</p><p>${esc(e.hotel)}</p></div><div class="panel"><h3>Competition</h3><p>${fmt(e.start)}–${fmt(e.end)}</p><p>${esc(e.rule)}</p></div><div class="panel"><h3>Weekend prep</h3><p>${e.athletes} watched athletes • ${esc(e.weather)}</p></div></div>`;s.classList.add('show');$('#close').onclick=()=>s.classList.remove('show');}
function openPass(id){const a=athletes.find(x=>x.id===id);if(!a)return;const s=$('#sheet');s.innerHTML=`<button class="close" id="close">Close</button><div class="qr">▦</div><h2>${esc(a.name)}</h2><p>${esc(a.club)}</p><div class="panel"><p>${esc(a.ranking)}</p><p>Licence: ${esc(a.licence)}</p><p>Insurance: ${esc(a.insurance)}</p><p>Medical: ${esc(a.medical)}</p></div>`;s.classList.add('show');$('#close').onclick=()=>s.classList.remove('show');}
function openReplay(id){const e=events.find(x=>x.id===id);if(!e)return;const s=$('#sheet');s.innerHTML=`<button class="close" id="close">Close</button><h2>🎬 ${esc(e.name)} Replay</h2><div class="replay-banner" style="--image:${esc(e.image)}"></div><div class="grid"><div class="panel"><h3>Journey</h3><p>${esc(e.travel)}</p><p>${fmt(e.start)}–${fmt(e.end)}</p></div><div class="panel"><h3>Team result</h3><p>3 medals • 7 wins • 4 personal bests</p></div><div class="panel"><h3>Media</h3><p>12 photos • 3 videos • 1 highlight reel</p></div></div>`;s.classList.add('show');$('#close').onclick=()=>s.classList.remove('show');}
function download(name,text,type='text/plain'){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500);}
function bind(){
 $$('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render();});
 $$('[data-open]').forEach(b=>b.onclick=e=>{e.stopPropagation();openEvent(b.dataset.open);});
 $$('[data-save]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.save;state.saved.has(id)?state.saved.delete(id):state.saved.add(id);saveStore();render();});
 $$('[data-pass]').forEach(b=>b.onclick=()=>openPass(b.dataset.pass));
 $$('[data-replay]').forEach(b=>b.onclick=()=>openReplay(b.dataset.replay));
 $$('[data-report]').forEach(b=>b.onclick=()=>{const e=events.find(x=>x.id===b.dataset.report);download(`${e.id}-report.txt`,`${e.name}\n${fmt(e.start)}\nTeam medals: 3\nWins: 7\nHighlights: 4 personal bests`);});
 const q=$('#search');if(q)q.oninput=e=>{state.query=e.target.value;clearTimeout(window.__q);window.__q=setTimeout(render,120)};
 const f=$('#filter');if(f)f.onchange=e=>{state.filter=e.target.value;render()};
 $$('[data-filter-stat]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filterStat;render();});
 const reset=$('#reset');if(reset)reset.onclick=()=>{state.query='';state.filter='All';render()};
 $$('[data-budget]').forEach(i=>i.onchange=e=>{state.budget[e.target.dataset.budget]=Number(e.target.value)||0;saveStore();render()});
 $$('[data-att]').forEach(i=>i.onchange=e=>{state.attendance[e.target.dataset.att]=e.target.checked;saveStore();});
 const theme=$('#themeBtn');if(theme)theme.onclick=()=>document.body.classList.toggle('light');
 const sync=$('#syncNow');if(sync)sync.onclick=()=>notify('Sync complete: local data and offline cache are healthy.');
 const tests=$('#runTests');if(tests)tests.onclick=()=>notify(`Tests passed: ${events.length} events, ${athletes.length} athletes, ${duplicateIds(events)} duplicate IDs.`);
 const exp=$('#teamExport');if(exp)exp.onclick=()=>download('fighteye-team-list.txt',athletes.map(a=>`${a.name} | ${a.ranking} | ${a.licence} | ${a.medical}`).join('\n'));
 const comp=$('#checkCompliance');if(comp)comp.onclick=()=>notify('Compliance check complete: one licence or passport item needs attention.');
 const slider=$('#rankSlider');if(slider)slider.oninput=e=>{state.rankFinish=Number(e.target.value);render();};
 const season=$('#seasonExport');if(season)season.onclick=()=>download('fighteye-season-plan.txt','Recommended season plan\n1. GB Grand Slam 2\n2. WAKO Junior Worlds\n3. ICO English Open');
 const pa=$('#parentAthlete');if(pa)pa.onchange=e=>{state.parentAthlete=e.target.value;saveStore();render();};
 const share=$('#familyShare');if(share)share.onclick=()=>{const a=athletes.find(x=>x.id===state.parentAthlete)||athletes[0];download(`${a.id}-family-briefing.txt`,`${a.name} family briefing\nNext event: ${a.next}\nBring licence, uniform, equipment, water and medication.`);};
 const form=$('#eventForm');if(form)form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form),start=fd.get('start'),closing=fd.get('closing'),name=String(fd.get('name')).trim();const item={id:`custom-${Date.now()}`,name,org:String(fd.get('org')).trim(),country:'United Kingdom',flag:'🇬🇧',city:String(fd.get('city')).trim(),venue:'Venue TBC',start,end:start,closing,collection:['UK'],rule:'Categories TBC',athletes:0,difficulty:2,cost:'£',weather:'TBC',distance:'TBC',image:'linear-gradient(135deg,#071b3a,#d6a441)',registration:'#',hotel:'TBC',travel:'TBC'};state.adminEvents.push(item);events.push({...item,status:statusFor(item)});events.sort((a,b)=>new Date(a.start)-new Date(b.start));saveStore();notify(`${name} added.`);};
 const validate=$('#validateLinks');if(validate)validate.onclick=()=>notify(`${invalidEvents().length} invalid records; ${events.filter(e=>e.registration==='#').length} registration links need updating.`);
 const exportData=$('#exportData');if(exportData)exportData.onclick=()=>download('fighteye-data-backup.json',JSON.stringify({events,athletes,saved:[...state.saved]},null,2),'application/json');
 const health=$('#healthCheck');if(health)health.onclick=async()=>{state.apiHealth='Checking…';render();try{const r=await fetch('/.netlify/functions/health',{headers:{'Accept':'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();state.apiHealth=d.ok?'Healthy':'Degraded';}catch{state.apiHealth='Local fallback active';}render();};
 const persist=$('#persistenceTest');if(persist)persist.onclick=()=>{try{const k='fighteye-persistence-test';localStorage.setItem(k,'ok');const ok=localStorage.getItem(k)==='ok';localStorage.removeItem(k);notify(ok?'Persistence test passed.':'Persistence test failed.');}catch{notify('Persistence unavailable in this browser.');}};
 const source=$('#integrationSource');if(source)source.onchange=e=>{state.integrationSource=e.target.value;render();};
 const runSync=$('#runIntegrationSync');if(runSync)runSync.onclick=async()=>{const candidates=events.filter(e=>state.integrationSource==='All'||e.org===state.integrationSource);const ids=new Set();let duplicates=0,invalid=0,accepted=0;candidates.forEach(e=>{if(!e.id||!e.name||!e.start){invalid++;return}if(ids.has(e.id)){duplicates++;return}ids.add(e.id);accepted++;});state.syncReport={source:state.integrationSource,checked:candidates.length,accepted,duplicates,invalid,at:new Date().toISOString()};notify(`Sync complete: ${accepted} accepted, ${duplicates} duplicates blocked.`);};
 const exportSync=$('#exportSync');if(exportSync)exportSync.onclick=()=>download('fighteye-sync-report.json',JSON.stringify(state.syncReport||{message:'No sync has been run'},null,2),'application/json');
 const aa=$('#analyticsAthlete');if(aa)aa.onchange=e=>{state.analyticsAthlete=e.target.value;saveStore();render();};
 const ag=$('#analyticsGoal');if(ag)ag.onchange=e=>{state.analyticsGoal=e.target.value;saveStore();render();};
 const ae=$('#analyticsExport');if(ae)ae.onclick=()=>{const a=athletes.find(x=>x.id===state.analyticsAthlete)||athletes[0];download(`${a.id}-analytics.json`,JSON.stringify({release:VERSION,athlete:a,goal:state.analyticsGoal,eventCount:events.length,generatedAt:new Date().toISOString()},null,2),'application/json');};
 const prod=$('#runProductionChecks');if(prod)prod.onclick=async()=>{const tests=[{name:'Event data valid',ok:invalidEvents().length===0},{name:'Unique event IDs',ok:duplicateIds(events)===0},{name:'Local storage available',ok:(()=>{try{localStorage.setItem('__fe','1');localStorage.removeItem('__fe');return true}catch{return false}})()},{name:'Fetch API available',ok:typeof fetch==='function'},{name:'Service worker supported',ok:'serviceWorker' in navigator},{name:'Secure context or localhost',ok:window.isSecureContext||location.hostname==='localhost'}];state.productionReport={tests,passed:tests.filter(t=>t.ok).length,failed:tests.filter(t=>!t.ok).length,at:new Date().toISOString()};render();};
 const ph=$('#productionHealth');if(ph)ph.onclick=async()=>{try{const [h,m]=await Promise.all([fetch('/.netlify/functions/health'),fetch('/.netlify/functions/metrics')]);if(!h.ok||!m.ok)throw new Error();state.apiHealth='Healthy';notify('API and metrics endpoints are healthy.');}catch{state.apiHealth='Local fallback active';notify('Remote functions unavailable; local fallback remains active.');}};
 const cc=$('#clearCaches');if(cc)cc.onclick=async()=>{if('caches'in window){for(const k of await caches.keys())await caches.delete(k);notify('Application caches cleared. Reload to refresh assets.');}else notify('Cache API is not available.');};
 const ed=$('#exportDiagnostics');if(ed)ed.onclick=()=>download('fighteye-production-diagnostics.json',JSON.stringify({version:VERSION,apiHealth:state.apiHealth,events:events.length,athletes:athletes.length,duplicates:duplicateIds(events),invalid:invalidEvents().length,online:navigator.onLine,report:state.productionReport,generatedAt:new Date().toISOString()},null,2),'application/json');
 const clear=$('#clearCustom');if(clear)clear.onclick=()=>{const ids=new Set(state.adminEvents.map(e=>e.id));for(let i=events.length-1;i>=0;i--)if(ids.has(events[i].id))events.splice(i,1);state.adminEvents=[];saveStore();notify('Custom events removed.');};
}
window.addEventListener('DOMContentLoaded',()=>{render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});});
})();
