const fs=require('fs');const path=require('path');const assert=require('assert');const vm=require('vm');const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');const app=fs.readFileSync(path.join(root,'app.js'),'utf8');const data=fs.readFileSync(path.join(root,'data/events-api.json'),'utf8');const events=JSON.parse(data);
assert(html.includes('app.js'),'index references app.js');assert(app.includes('analyticsView'),'analytics view present');assert(app.includes('productionView'),'production view present');
assert(events.length>=25,'expanded event dataset present');assert.strictEqual(new Set(events.map(e=>e.id)).size,events.length,'event IDs unique');
for(const e of events){for(const k of ['id','name','org','start','end'])assert(e[k],`missing ${k}`);assert(e.start<=e.end,`invalid dates: ${e.id}`);if(e.source)assert(e.sourceUrl?.startsWith('https://'),`missing listing: ${e.id}`);}
assert(events.filter(e=>e.country==='United Kingdom').length>=15,'UK competition coverage');
assert.strictEqual(events.find(e=>e.id==='peterborough-series-3-2026').closing,'2026-10-25','Peterborough published closing date');
assert.strictEqual(events.find(e=>e.id==='wku-english-open-2027').start,'2027-01-30','WKU 2027 date');
assert(app.includes('seriesFilter'),'organiser filter present');
assert(app.includes('kindFilter'),'activity filter present');
assert(app.includes('refreshPublishedEvents();'),'weekly client refresh present');
assert(app.includes('Subscribe in Calendar')&&app.includes('ICLOUD_FEED'),'iCloud subscription action present');
assert.strictEqual(events.find(e=>e.id==='gb-grand-slam-2-2026').start,'2026-07-11','Crawley Grand Slam corrected');
assert.strictEqual(events.filter(e=>e.series==='GB Grand Slam').length,4,'four dated GB Grand Slams');
assert.strictEqual(events.find(e=>e.id==='ico-england-squad-oct-2026').access,'Open','ICO squad is open');
assert.strictEqual(events.find(e=>e.id==='kbgb-tatami-squad-nov-2026').access,'Eligibility to confirm','GB eligibility not assumed');
assert.strictEqual(events.find(e=>e.id==='bristol-open-2026').start,'2026-10-23','Bristol Open uses published date');
const store=new Map();
const context={window:{FIGHTEYE_EVENTS:events,FIGHTEYE_ATHLETES:[{id:'test-athlete',name:'Test Athlete',ranking:'Cadet',weight:'42 kg'}],addEventListener:()=>{},webkit:{messageHandlers:{fighteyeHealth:{postMessage:()=>{}}}}},document:{getElementById:()=>({}),querySelector:()=>null,querySelectorAll:()=>[]},localStorage:{getItem:key=>store.get(key)||null,setItem:(key,value)=>store.set(key,value)},navigator:{},URL};
vm.runInNewContext(app.replace('})();','globalThis.__events={statusFor,eventsView,settingsView,clubView,passportView,nav,registrationOpen,calendarText,clubWebsite,parseHealthWeightXML,receiveHealthResult,validateWeightBackup,visibleWeights,weightText,state};})();'),context);
assert.strictEqual(context.__events.statusFor({start:'2099-01-01',end:'2099-01-02',closing:null}),'Date confirmed • entry TBC');
assert(context.__events.eventsView().includes('data-event-period="past"'),'past events tab present');
assert(context.__events.eventsView().includes('data-event-period="open"'),'registration tab present');
assert(context.__events.eventsView().includes('data-calendar='),'calendar action on event cards');
assert(!context.__events.eventsView().includes('Subscribe in Calendar'),'subscription moved off Events');
assert(context.__events.settingsView().includes('Subscribe in Calendar'),'subscription in Settings');
assert(context.__events.settingsView().includes('Apple Health privacy notice'),'Health privacy link in Settings');
assert(context.__events.nav().includes('data-tab="settings"'),'Settings in bottom navigation');
assert(context.__events.clubView().includes('Injury tracker'),'injury option in ClubOS');
assert(context.__events.clubView().includes('data-injury-athlete="test-athlete"'),'injury action on club athlete card');
assert(context.__events.passportView().includes('data-injury-athlete="test-athlete"'),'injury action on Passport card');
assert(context.__events.passportView().includes('athlete-affiliations'),'club and nationality marks on Passport');
context.__events.state.clubForm='injury';context.__events.state.injuryAthleteId='test-athlete';
assert(context.__events.passportView().includes('Private injury tracker'),'selected athlete opens private tracker inline');
context.__events.state.injuryKey={};
assert(context.__events.passportView().includes('name="severity"'),'injury severity field present');
assert(context.__events.passportView().includes('name="treatment"'),'treatment field present');
assert(context.__events.passportView().includes('name="duration"'),'expected injury length field present');
context.__events.state.clubForm='';context.__events.state.injuryAthleteId='';context.__events.state.injuryKey=null;
assert(context.__events.clubView().includes('Edit club details'),'club title edit present');
assert(context.__events.clubView().includes('assets/prestige-martial-arts.webp'),'verified Prestige logo shown');
assert(context.__events.clubView().includes('Radford Road, Nottingham NG7 7AB'),'verified address shown');
assert(context.__events.clubView().includes('07533 713584')&&context.__events.clubView().includes('prestigemartialart@icloud.com'),'verified contacts shown');
assert(context.__events.passportView().includes('assets/prestige-martial-arts.webp'),'athlete affiliation shows club logo');
context.__events.state.groups[0].email='custom@example.org';
assert(context.__events.clubView().includes('custom@example.org'),'edited club contact overrides official listing');
delete context.__events.state.groups[0].email;
assert(context.__events.clubView().includes('data-edit-athlete="test-athlete"'),'athlete edit present');
context.__events.state.editAthlete='test-athlete';
assert(context.__events.clubView().includes('name="photo" type="file"'),'athlete photo upload present');
assert(context.__events.clubView().includes('name="emergencyPhone"'),'emergency contact editable');
assert(context.__events.clubView().includes('name="groups"'),'club membership editable');
assert(context.__events.passportView().includes('Edit profile'),'passport profile editing present');
assert(context.__events.clubView().includes('data-result-form="test-athlete"'),'annual record editor in ClubOS');
context.window.FIGHTEYE_ATHLETES[0].annualResults=[{year:2026,organisation:'WAKO',gold:2,silver:1,bronze:3}];
assert(context.__events.passportView().includes('2026 • WAKO'),'organisation and year shown in Passport');
assert(context.__events.passportView().includes('🥇 2 · 🥈 1 · 🥉 3'),'medal totals shown in Passport');
assert(context.__events.clubView().includes('data-weight-form="test-athlete"'),'manual weight entry in ClubOS');
assert(context.__events.clubView().includes('data-weight-range="30"'),'weight history ranges present');
assert(context.__events.clubView().includes('data-export-weight="test-athlete"'),'weight-only backup action present');
assert(context.__events.clubView().includes('data-import-weight="test-athlete"'),'weight backup restore present');
assert.strictEqual(context.__events.validateWeightBackup({schema:'fighteye-weight-v1',athlete:{name:'Test Athlete'},records:[{date:'2026-09-20',kg:43,source:'Manual'}]}).length,1,'valid weight backup accepted');
assert.throws(()=>context.__events.validateWeightBackup({schema:'fighteye-weight-v1',athlete:{name:'Test Athlete'},records:[{date:'2026-09-20',kg:43,source:'Manual'},{date:'2026-09-20',kg:44,source:'Manual'}]}),'duplicate backup dates rejected');
assert(context.__events.passportView().includes('data-health-import="test-athlete"'),'Health XML import in Passport');
assert(context.__events.passportView().includes('Connect Apple Health'),'native Health connection offered');
context.__events.receiveHealthResult({athleteId:'test-athlete',status:'syncing'});
assert(context.__events.passportView().includes('Syncing body mass'),'sync progress shown');
context.__events.receiveHealthResult({athleteId:'test-athlete',status:'synced',backgroundEnabled:true,lastSync:'2026-09-27T17:00:00Z',samples:[{date:'2026-09-26',kg:42.4},{date:'2026-09-27',kg:43.1}]});
assert.strictEqual(context.__events.state.weightRecords['test-athlete'].length,2,'native weight samples stored');
assert(context.__events.passportView().includes('43.1 kg'),'latest Health weight displayed');
assert(context.__events.passportView().includes('last read'),'last Health read shown');
assert(context.__events.passportView().includes('Health changes can notify'),'background delivery status shown');
context.__events.state.weightRecords['test-athlete'].push({date:'2026-09-28',kg:44,source:'Manual'});
context.__events.receiveHealthResult({athleteId:'test-athlete',samples:[{date:'2026-09-28',kg:50},{date:'2026-09-27',kg:43.5},{date:'2026-09-27',kg:41}]});
assert.strictEqual(context.__events.state.weightRecords['test-athlete'].find(r=>r.date==='2026-09-28').kg,44,'manual weight takes precedence');
assert.strictEqual(context.__events.state.weightRecords['test-athlete'].find(r=>r.date==='2026-09-27').kg,43.5,'newest Health sample for a date wins');
context.__events.receiveHealthResult({athleteId:'test-athlete',status:'synced',complete:true,windowStart:'2026-09-01',samples:[{date:'2026-09-27',kg:43.5}]});
assert(!context.__events.state.weightRecords['test-athlete'].some(r=>r.date==='2026-09-26'),'deleted Health date reconciled');
assert.strictEqual(context.__events.state.weightRecords['test-athlete'].find(r=>r.date==='2026-09-28').kg,44,'manual date survives reconciliation');
context.__events.state.weightUnit='lb';
assert.strictEqual(context.__events.weightText(50),'110.2 lb','pounds display conversion');
context.__events.receiveHealthResult({athleteId:'unknown',samples:[{date:'2026-09-27',kg:99}]});
assert(!context.__events.state.weightRecords.unknown,'unknown athlete ignored');
context.__events.receiveHealthResult({athleteId:'',status:'disconnected'});
assert(context.__events.passportView().includes('Connect Apple Health'),'disconnect restores connect action');
const weights=context.__events.parseHealthWeightXML('<HealthData><Record type="HKQuantityTypeIdentifierBodyMass" startDate="2026-09-20 07:00:00 +0100" unit="lb" value="110"/><Record type="HKQuantityTypeIdentifierHeartRate" startDate="2026-09-20 07:00:00 +0100" unit="count/min" value="70"/></HealthData>');
assert.strictEqual(weights.length,1,'only body mass records imported');
assert.strictEqual(weights[0].kg,49.9,'pounds converted to kilograms');
context.window.FIGHTEYE_ATHLETES[0].photo='data:image/jpeg;base64,YWJj';
assert(context.__events.passportView().includes('class="avatar athlete-photo"'),'passport shows athlete photo');
context.__events.state.editAthlete='';
context.__events.state.clubForm='details';
assert(context.__events.clubView().includes('name="logo"'),'club logo upload present');
assert.strictEqual(context.__events.clubWebsite('javascript:alert(1)'),'','unsafe website rejected');
context.__events.state.clubForm='injury';
assert(context.__events.clubView().includes('injuryUnlock'),'injury records locked by default');
const ics=context.__events.calendarText({id:'test',name:'Open, Finals',org:'Test',city:'Leeds',country:'United Kingdom',venue:'Arena',start:'2027-07-10',end:'2027-07-11',sourceUrl:'https://example.org/event'});
assert(ics.includes('DTSTART;VALUE=DATE:20270710'),'calendar starts on event date');
assert(ics.includes('DTEND;VALUE=DATE:20270712'),'calendar includes final day');
assert(ics.includes('SUMMARY:Open\\, Finals'),'calendar text escaped');
assert(ics.includes('URL:https://example.org/event'),'calendar links to organiser');
const future=new Date(Date.now()+40*86400000).toISOString().slice(0,10), closing=new Date(Date.now()+20*86400000).toISOString().slice(0,10), expired=new Date(Date.now()-86400000).toISOString().slice(0,10);
assert(context.__events.registrationOpen({start:future,end:future,closing},new Date().toISOString().slice(0,10)),'future competition accepting entries');
assert(!context.__events.registrationOpen({start:future,end:future,closing:expired},new Date().toISOString().slice(0,10)),'closed registration excluded');
assert(!context.__events.registrationOpen({kind:'Squad training',start:future,end:future,closing},new Date().toISOString().slice(0,10)),'training excluded');
for(const f of ['styles.css','sw.js','manifest.json','netlify.toml','netlify/functions/analytics.js','netlify/functions/metrics.js'])assert(fs.existsSync(path.join(root,f)),`missing ${f}`);
console.log(`Smoke tests passed: ${events.length} events, unique IDs, analytics and production modules present.`);
